---
title: |
  Only You: A Field Experiment of Text Message
  to Prevent Free-riding in Japan Marrow Donor Program
subtitle: Field Experiment (Appendix)
---

```{r include=FALSE}
library(here)
source(here("R", "_library.r"))
source(here("R", "_outcome_labels.r"))
```

```{r load-data, echo = FALSE, message=FALSE}
root <- "D:/JMDPフィールド実験"

rawdt <- read_csv(
  here(root, "shaped.csv"),
  locale = locale(encoding = "cp932")
)

use <- rawdt %>%
  dplyr::filter(ongoing == 0) %>%
  mutate(treat = factor(treat, levels = LETTERS[1:4]))
```

```{r exogenous-attrition, echo=FALSE, message=FALSE}
exclude_data <- use %>%
  select(treat, RCTweek, starts_with("exg_stop")) %>%
  pivot_longer(
    - (treat:RCTweek),
    names_to = "outcome", values_to = "exclude",
    names_prefix = "exg_stop_"
  )

exclude_balance <- exclude_data %>%
  group_by(outcome) %>%
  nest() %>%
  mutate(est = map(
    data,
    ~lm_robust(exclude ~ treat, data = .x, cluster = RCTweek, se_type = "stata")
  )) %>%
  mutate(
    f = map_dbl(est, ~ summary(.x)$fstatistic[1]),
    numdf = map_dbl(est, ~ summary(.x)$fstatistic[2]),
    dendf = map_dbl(est, ~ summary(.x)$fstatistic[3]),
    p = pf(f, numdf, dendf, lower.tail = FALSE),
    "p-value" = sprintf("%1.3f", p)
  ) %>%
  select(outcome, "p-value") %>%
  dplyr::filter(outcome != "intention") %>%
  mutate(outcome = factor(
    outcome,
    levels = names(outcome_label)[c(1, 4:7)],
    labels = unlist(outcome_label[c(1, 4:7)])
  ))

exclude_data %>%
  dplyr::filter(outcome != "intention") %>%
  mutate(outcome = factor(
    outcome,
    levels = names(outcome_label)[c(1, 4:7)],
    labels = unlist(outcome_label[c(1, 4:7)])
  )) %>%
  datasummary(
    (`Outcome variables` = outcome) ~ exclude * mean * treat,
    data = .,
    fmt = 3,
    title = "Balance Test of Exogenous Termination of The Coordination",
    add_columns = exclude_balance[, 2],
    align = "lccccc"
  ) %>%
  kableExtra::kable_styling() %>%
  add_header_above(c(" " = 1, "Experimental Arms" = 4, " " = 1))
```