
```{r load-packages, include = FALSE}
library(here)
source(here("R", "_library.r"))
source(here("R", "_outcome_labels.r"))
```

```{r load-data, include = FALSE}
root <- "D:/JMDPフィールド実験"

rawdt <- read_csv(
  here(root, "shaped.csv"),
  locale = locale(encoding = "cp932")
)

use <- rawdt %>%
  mutate(treat = factor(treat, levels = LETTERS[1:4]))

outcomes <- use %>%
  select(
    id,
    treat,
    reply,
    intention:donate
  ) %>%
  pivot_longer(reply:donate, names_to = "outcome")

exclude <- use %>%
  select(id, starts_with("exg_stop")) %>%
  pivot_longer(
    -id, names_to = "outcome", values_to = "exclude",
    names_prefix = "exg_stop_"
  )

testdt <- outcomes %>%
  dplyr::left_join(exclude, by = c("id", "outcome")) %>%
  dplyr::filter(exclude == 0)
```

## アウトカム変数

アウトカム変数は提供に至るまでのプロセスであり、具体的に以下の6つの工程がある。

- Reply to notification: 適合通知に返信したならば1を取る二値変数
- Intention: 提供を希望するという意向を示して返信したならば1を取る二値変数
- Confirmatory typing: 確認検査を実施したならば1を取る二値変数
- Candidate: 第一候補者に選定されたならば1を取る二値変数
- Final consent: 最終同意をしたならば1を取る二値変数
- Donation: 採取をしたならば1を取る二値変数

```{r ttest, include = FALSE}
stat <- testdt %>%
  group_by(outcome, treat) %>%
  summarize(mean = mean(value), se = se(value), n = n()) %>%
  ungroup() %>%
  mutate(
    lwr.mean = mean - se,
    upr.mean = mean + se,
    outcome = factor(outcome, out_lev, out_lab)
  )

ttest_info <- expand.grid(
  outcome = out_lev,
  group1 = LETTERS[1:4],
  group2 = LETTERS[1:4],
  stringsAsFactors = FALSE) %>%
  dplyr::filter(group1 < group2) %>%
  arrange(outcome) %>%
  mutate(id = seq(n()))

ttest <- ttest_info %>%
  group_by(id) %>%
  do(test = t.test(
    subset(
      testdt, treat == .$group1 & outcome == .$outcome
    )$value,
    subset(
      testdt, treat == .$group2 & outcome == .$outcome
    )$value
  )) %>%
  summarize(
    id = id,
    p = test$p.value,
    est1 = test$estimate[1],
    est2 = test$estimate[2]
  )

show_ttest_info <- ttest_info %>%
  dplyr::left_join(ttest, by = "id") %>%
  dplyr::filter(p <= 0.1) %>%
  mutate_at(vars(group1, group2), list(~factor(., levels = LETTERS[1:4]))) %>%
  mutate(outcome = factor(outcome, out_lev, out_lab)) %>%
  group_by(id) %>%
  do(data.frame(
    outcome = .$outcome,
    group1 = .$group1,
    group2 = .$group2,
    p = .$p,
    y_g1 = subset(stat, outcome == .$outcome & treat == .$group1)$upr.mean,
    y_g2 = subset(stat, outcome == .$outcome & treat == .$group2)$upr.mean
  )) %>%
  ungroup() %>%
  mutate(
    y = if_else(y_g1 > y_g2, y_g1, y_g2) + 0.02,
    y = if_else(id == 21, y + 0.02, y),
    y = if_else(id == 34, y + 0.06, y),
    sign = case_when(
      p < 0.01 ~ "***",
      p < 0.05 ~ "**",
      p < 0.1 ~ "*",
      TRUE ~ "",
    )
  )
```


## 返信～確認検査の二群比較の検定


```{r ttest-1-3step, echo = FALSE}
stat %>%
  dplyr::filter(outcome %in% out_lab[1:3]) %>%
  ggplot(aes(x = treat, y = mean)) +
    geom_bar(
      color = "black",
      fill = "grey90",
      stat = "identity"
    ) +
    geom_errorbar(
      aes(ymin = lwr.mean, ymax = upr.mean),
      width = 0.5, position = position_dodge(0.9)
    ) +
    geom_text(
      aes(y = 0, label = sprintf("%1.3f\nN=%1d", mean, n)),
      vjust = -1, size = 3
    ) +
    geom_signif(
      data = show_ttest_info,
      aes(xmin = group1, xmax = group2, annotations = sign, y_position = y),
      textsize = 5, tip_length = 0.01,
      manual = TRUE
    ) +
    facet_wrap(~ outcome) +
    scale_y_continuous(breaks = seq(0, 1, 0.1)) +
    labs(
      x = "Experimental Arms",
      y = "Sample average",
      caption = "*** p < 0.01, ** p < 0.05, * p < 0.1"
    ) +
    simplegg(caption_size = 13)
```

## 候補者選定～採血までの二群比較の検定

```{r ttest-4-6step, echo = FALSE}
stat %>%
  dplyr::filter(outcome %in% out_lab[4:6]) %>%
  ggplot(aes(x = treat, y = mean)) +
    geom_bar(
      color = "black",
      fill = "grey90",
      stat = "identity"
    ) +
    geom_errorbar(
      aes(ymin = lwr.mean, ymax = upr.mean),
      width = 0.5, position = position_dodge(0.9)
    ) +
    geom_text(
      aes(y = 0, label = sprintf("%1.3f\nN=%1d", mean, n)),
      vjust = -1, size = 3
    ) +
    facet_wrap(~ outcome) +
    scale_y_continuous(
      limits = c(0, 0.16),
      breaks = seq(0, 0.16, 0.02)
    ) +
    labs(
      x = "Experimental Arms",
      y = "Sample average",
      fill = "Experimental Arms"
    ) +
    simplegg()
```

