
```{r load-packages, include = FALSE}
library(here)
source(here("R", "_library.r"))
source(here("R", "_outcome_labels.r"))
```

```{r load-data, include = FALSE}
root <- "D:/JMDPフィールド実験"

rawdt <- read_csv(
  here(root, "shaped.csv"),
  locale = locale(encoding = "cp932")
)

use <- rawdt %>%
  mutate(treat = factor(treat, levels = LETTERS[1:4]))

outcomes <- use %>%
  select(
    id,
    reply,
    intention,
    test,
    candidate,
    consent,
    donate,
    days_reply,
    treat,
    RCTweek,
    month,
    week,
    prefecture,
    male,
    age,
    coordinate
  ) %>%
  pivot_longer(reply:donate, names_to = "outcome")

exclude <- use %>%
  select(id, starts_with("exg_stop")) %>%
  pivot_longer(
    -id, names_to = "outcome", values_to = "exclude",
    names_prefix = "exg_stop_"
  )

testdt <- outcomes %>%
  dplyr::left_join(exclude, by = c("id", "outcome")) %>%
  dplyr::filter(exclude == 0 & prefecture != "海外") %>%
  mutate(
    outcome = factor(outcome, out_lev, out_lab),
    prefecture = factor(prefecture, c("東京都", unique(rawdt$prefecture)[-11])),
    age30 = if_else(age <= 30, 1, 0),
    coordinate1 = if_else(coordinate == 1, 1, 0)
  )
```

## 異質性の検討

- 性別と年齢（30歳以下どうか）でサンプルを分割して、
各サブサンプル内でメッセージの効果を推定した

```{r heterogenity}
est <- testdt %>%
  group_by(outcome, male, age30) %>%
  do(est = lm_robust(
    value ~ treat + coordinate + prefecture + factor(month) + factor(week),
    cluster = RCTweek,
    se_type = "stata",
    data = .
  ))
```

## 性別・年齢層別のメッセージBの効果

```{r heterogenous-effect-B, fig.width = 10, fig.height=7}
est %>%
  rowwise(outcome, male, age30) %>%
  summarize(
    estimate = subset(tidy(est), term == "treatB")$estimate,
    conf.low = subset(tidy(est), term == "treatB")$conf.low,
    conf.high = subset(tidy(est), term == "treatB")$conf.high,
    nobs = nobs(est)
  ) %>%
  ungroup() %>%
  mutate(
    pos = paste0(male, age30),
    N = paste0("N=", nobs)
  ) %>%
  ggplot(aes(x = pos, y = estimate)) +
    geom_hline(aes(yintercept = 0), linetype = 2) +
    geom_pointrange(aes(ymin = conf.low, ymax = conf.high)) +
    geom_text(aes(y = -0.15, label = N)) +
    facet_wrap(~ outcome, ncol = 3) +
    scale_y_continuous(breaks = seq(-0.2, 0.2, by = 0.05)) +
    scale_x_discrete(
      breaks = c("00", "01", "10", "11"),
      labels = c(
        "Female\u00d730<Age",
        "Female\u00d730\u2265Age",
        "Male\u00d730<Age",
        "Male\u00d730\u2265Age"
      )
    ) +
    labs(x = "Subset", y = "Estimate (95%CI)") +
    simplegg() +
    theme(axis.text.x = element_text(angle = 45, vjust = 1, hjust = 1))
```

## 性別・年齢層別のメッセージCの効果

```{r heterogenous-effect-C, fig.width = 10, fig.height=7}
est %>%
  rowwise(outcome, male, age30) %>%
  summarize(
    estimate = subset(tidy(est), term == "treatC")$estimate,
    conf.low = subset(tidy(est), term == "treatC")$conf.low,
    conf.high = subset(tidy(est), term == "treatC")$conf.high,
    nobs = nobs(est)
  ) %>%
  ungroup() %>%
  mutate(
    pos = paste0(male, age30),
    N = paste0("N=", nobs)
  ) %>%
  ggplot(aes(x = pos, y = estimate)) +
    geom_hline(aes(yintercept = 0), linetype = 2) +
    geom_pointrange(aes(ymin = conf.low, ymax = conf.high)) +
    geom_text(aes(y = -0.15, label = N)) +
    facet_wrap(~ outcome, ncol = 3) +
    scale_y_continuous(breaks = seq(-0.2, 0.2, by = 0.05)) +
    scale_x_discrete(
      breaks = c("00", "01", "10", "11"),
      labels = c(
        "Female\u00d730<Age",
        "Female\u00d730\u2265Age",
        "Male\u00d730<Age",
        "Male\u00d730\u2265Age"
      )
    ) +
    labs(x = "Subset", y = "Estimate (95%CI)") +
    simplegg() +
    theme(axis.text.x = element_text(angle = 45, vjust = 1, hjust = 1))
```

## 性別・年齢層別のメッセージDの効果

```{r heterogenous-effect-D, fig.width = 10, fig.height=7}
est %>%
  rowwise(outcome, male, age30) %>%
  summarize(
    estimate = subset(tidy(est), term == "treatD")$estimate,
    conf.low = subset(tidy(est), term == "treatD")$conf.low,
    conf.high = subset(tidy(est), term == "treatD")$conf.high,
    nobs = nobs(est)
  ) %>%
  ungroup() %>%
  mutate(
    pos = paste0(male, age30),
    N = paste0("N=", nobs)
  ) %>%
  ggplot(aes(x = pos, y = estimate)) +
    geom_hline(aes(yintercept = 0), linetype = 2) +
    geom_pointrange(aes(ymin = conf.low, ymax = conf.high)) +
    geom_text(aes(y = -0.15, label = N)) +
    facet_wrap(~ outcome, ncol = 3) +
    scale_y_continuous(breaks = seq(-0.2, 0.2, by = 0.05)) +
    scale_x_discrete(
      breaks = c("00", "01", "10", "11"),
      labels = c(
        "Female\u00d730<Age",
        "Female\u00d730\u2265Age",
        "Male\u00d730<Age",
        "Male\u00d730\u2265Age"
      )
    ) +
    labs(x = "Subset", y = "Estimate (95%CI)") +
    simplegg() +
    theme(axis.text.x = element_text(angle = 45, vjust = 1, hjust = 1))
```

## 返信スピードへの効果（30歳以上の女性）

```{r plot-reply-days-female-over30}
log.rank <- testdt %>%
  dplyr::filter(male == 0 & age30 == 0) %>%
  dplyr::filter(outcome == "Reply") %>%
  mutate(days_reply = if_else(
    is.na(days_reply),
    max(use$days_reply, na.rm = TRUE),
    days_reply
  )) %>%
  survdiff(Surv(days_reply, value) ~ treat, data = .)

p.log.rank <- 1 - pchisq(log.rank$chisq, 3)

testdt %>%
  dplyr::filter(male == 0 & age30 == 0) %>%
  dplyr::filter(outcome == "Reply") %>%
  mutate(days_reply = if_else(
    is.na(days_reply),
    max(use$days_reply, na.rm = TRUE),
    days_reply
  )) %>%
  survfit(Surv(days_reply, value) ~ treat, data = .) %>%
  tidy() %>%
  mutate(treat = str_extract(strata, "[A-D]")) %>%
  select(-strata) %>%
  ggplot(aes(x = time, y = 1 - estimate, group = treat)) +
    geom_line(aes(color = treat)) +
    annotate(
      geom = "text",
      x = 50, y = 0.6,
      label = sprintf(
        "Log-rank test\nchi-square = %1.3f; p-value = %1.3f",
        log.rank$chisq, p.log.rank
      ),
      size = 5
    ) +
    scale_y_continuous(breaks = seq(0, 1, 0.1)) +
    scale_x_continuous(breaks = seq(0, 90, 5)) +
    scale_color_hue() +
    labs(x = "Days", y = "Reply rates", color = "Experimental Arms") +
    simplegg()
```

## 返信スピードへの効果（30歳以下の女性）

```{r plot-reply-days-female-under30}
log.rank <- testdt %>%
  dplyr::filter(male == 0 & age30 == 1) %>%
  dplyr::filter(outcome == "Reply") %>%
  mutate(days_reply = if_else(
    is.na(days_reply),
    max(use$days_reply, na.rm = TRUE),
    days_reply
  )) %>%
  survdiff(Surv(days_reply, value) ~ treat, data = .)

p.log.rank <- 1 - pchisq(log.rank$chisq, 3)

testdt %>%
  dplyr::filter(male == 0 & age30 == 1) %>%
  dplyr::filter(outcome == "Reply") %>%
  mutate(days_reply = if_else(
    is.na(days_reply),
    max(use$days_reply, na.rm = TRUE),
    days_reply
  )) %>%
  survfit(Surv(days_reply, value) ~ treat, data = .) %>%
  tidy() %>%
  mutate(treat = str_extract(strata, "[A-D]")) %>%
  select(-strata) %>%
  ggplot(aes(x = time, y = 1 - estimate, group = treat)) +
    geom_line(aes(color = treat)) +
    annotate(
      geom = "text",
      x = 50, y = 0.6,
      label = sprintf(
        "Log-rank test\nchi-square = %1.3f; p-value = %1.3f",
        log.rank$chisq, p.log.rank
      ),
      size = 5
    ) +
    scale_y_continuous(breaks = seq(0, 1, 0.1)) +
    scale_x_continuous(breaks = seq(0, 90, 5)) +
    scale_color_hue() +
    labs(x = "Days", y = "Reply rates", color = "Experimental Arms") +
    simplegg()
```

## 返信スピードへの効果（30歳以上の男性）

```{r plot-reply-days-male-over30}
log.rank <- testdt %>%
  dplyr::filter(male == 1 & age30 == 0) %>%
  dplyr::filter(outcome == "Reply") %>%
  mutate(days_reply = if_else(
    is.na(days_reply),
    max(use$days_reply, na.rm = TRUE),
    days_reply
  )) %>%
  survdiff(Surv(days_reply, value) ~ treat, data = .)

p.log.rank <- 1 - pchisq(log.rank$chisq, 3)

testdt %>%
  dplyr::filter(male == 1 & age30 == 0) %>%
  dplyr::filter(outcome == "Reply") %>%
  mutate(days_reply = if_else(
    is.na(days_reply),
    max(use$days_reply, na.rm = TRUE),
    days_reply
  )) %>%
  survfit(Surv(days_reply, value) ~ treat, data = .) %>%
  tidy() %>%
  mutate(treat = str_extract(strata, "[A-D]")) %>%
  select(-strata) %>%
  ggplot(aes(x = time, y = 1 - estimate, group = treat)) +
    geom_line(aes(color = treat)) +
    annotate(
      geom = "text",
      x = 50, y = 0.6,
      label = sprintf(
        "Log-rank test\nchi-square = %1.3f; p-value = %1.3f",
        log.rank$chisq, p.log.rank
      ),
      size = 5
    ) +
    scale_y_continuous(breaks = seq(0, 1, 0.1)) +
    scale_x_continuous(breaks = seq(0, 90, 5)) +
    scale_color_hue() +
    labs(x = "Days", y = "Reply rates", color = "Experimental Arms") +
    simplegg()
```

## 返信スピードへの効果（30歳以下の男性）

```{r plot-reply-days-male-under30}
log.rank <- testdt %>%
  dplyr::filter(male == 1 & age30 == 1) %>%
  dplyr::filter(outcome == "Reply") %>%
  mutate(days_reply = if_else(
    is.na(days_reply),
    max(use$days_reply, na.rm = TRUE),
    days_reply
  )) %>%
  survdiff(Surv(days_reply, value) ~ treat, data = .)

p.log.rank <- 1 - pchisq(log.rank$chisq, 3)

testdt %>%
  dplyr::filter(male == 1 & age30 == 1) %>%
  dplyr::filter(outcome == "Reply") %>%
  mutate(days_reply = if_else(
    is.na(days_reply),
    max(use$days_reply, na.rm = TRUE),
    days_reply
  )) %>%
  survfit(Surv(days_reply, value) ~ treat, data = .) %>%
  tidy() %>%
  mutate(treat = str_extract(strata, "[A-D]")) %>%
  select(-strata) %>%
  ggplot(aes(x = time, y = 1 - estimate, group = treat)) +
    geom_line(aes(color = treat)) +
    annotate(
      geom = "text",
      x = 50, y = 0.6,
      label = sprintf(
        "Log-rank test\nchi-square = %1.3f; p-value = %1.3f",
        log.rank$chisq, p.log.rank
      ),
      size = 5
    ) +
    scale_y_continuous(breaks = seq(0, 1, 0.1)) +
    scale_x_continuous(breaks = seq(0, 90, 5)) +
    scale_color_hue() +
    labs(x = "Days", y = "Reply rates", color = "Experimental Arms") +
    simplegg()
```

## X日以内返信への効果の異質性（30歳以上の女性）

```{r heterogeneity-reply-until-days}
model <- value ~ treat + coordinate + prefecture + factor(month) + factor(week)

est_until_reply <- testdt %>%
  dplyr::filter(outcome == "Reply") %>%
  mutate(
    days_reply = if_else(
      is.na(days_reply),
      max(use$days_reply, na.rm = TRUE),
      days_reply
    ),
    value10 = if_else(days_reply <= 10, 1, 0),
    value20 = if_else(days_reply <= 20, 1, 0),
    value30 = if_else(days_reply <= 30, 1, 0),
    value40 = if_else(days_reply <= 40, 1, 0),
    value85 = value
  ) %>%
  select(-value) %>%
  pivot_longer(
    value10:value85,
    names_to = "until",
    names_prefix = "value"
  ) %>%
  mutate(until = factor(
    until,
    levels = c("10", "20", "30", "40", "85")
  )) %>%
  group_by(until, male, age30) %>%
  do(
    est = lm_robust(
      model,
      cluster = RCTweek,
      se_type = "stata",
      data = .
    ),
    ftestBC = lh_robust(
      model,
      cluster = RCTweek,
      se_type = "stata",
      linear_hypothesis = "treatB - treatC = 0",
      data = .
    )$lh,
    ftestBD = lh_robust(
      model,
      cluster = RCTweek,
      se_type = "stata",
      linear_hypothesis = "treatB - treatD = 0",
      data = .
    )$lh,
    ftestCD = lh_robust(
      model,
      cluster = RCTweek,
      se_type = "stata",
      linear_hypothesis = "treatC - treatD = 0",
      data = .
    )$lh
  )
```

```{r tab-reply-until-days-female-over30}
sub_est_until_reply <- est_until_reply %>%
  dplyr::filter(male == 0 & age30 == 0)

sub_est_until_reply %>%
  pull(est) %>%
  setNames(paste0("(", seq(length(sub_est_until_reply$est)), ")")) %>%
  modelsummary(
    stars = c("*" = 0.1, "**" = 0.05, "***" = 0.01),
    coef_map = c(
      "treatB" = "B",
      "treatC" = "C",
      "treatD" = "D"
    ),
    gof_omit = "R2|AIC|BIC|Log|Std|FE|se_type",
    add_rows = bind_rows(sub_est_until_reply$ftestBC)[, 4] %>%
      rbind(bind_rows(sub_est_until_reply$ftestBD)[, 4]) %>%
      rbind(bind_rows(sub_est_until_reply$ftestCD)[, 4]) %>%
      data.frame(term = c("B = C", "B = D", "C = D"), .)
  ) %>%
  kableExtra::kable_styling(font_size = 9) %>%
  kableExtra::add_header_above(c(
    " " = 1, "\u2266 10days" = 1,
    "\u2266 20days" = 1, "\u2266 30days" = 1,
    "\u2266 40days" = 1, "\u2266 85days" = 1
  )) %>%
  kableExtra::column_spec(2:6, width = "5em") %>%
  kableExtra::group_rows(
    "F-tests, p-value", 8, 10,
    bold = FALSE, italic = TRUE
  )
```

## X日以内返信への効果の異質性（30歳以下の女性）

```{r tab-reply-until-days-female-under30}
sub_est_until_reply <- est_until_reply %>%
  dplyr::filter(male == 0 & age30 == 0)

sub_est_until_reply %>%
  pull(est) %>%
  setNames(paste0("(", seq(length(sub_est_until_reply$est)), ")")) %>%
  modelsummary(
    stars = c("*" = 0.1, "**" = 0.05, "***" = 0.01),
    coef_map = c(
      "treatB" = "B",
      "treatC" = "C",
      "treatD" = "D"
    ),
    gof_omit = "R2|AIC|BIC|Log|Std|FE|se_type",
    add_rows = bind_rows(sub_est_until_reply$ftestBC)[, 4] %>%
      rbind(bind_rows(sub_est_until_reply$ftestBD)[, 4]) %>%
      rbind(bind_rows(sub_est_until_reply$ftestCD)[, 4]) %>%
      data.frame(term = c("B = C", "B = D", "C = D"), .)
  ) %>%
  kableExtra::kable_styling(font_size = 9) %>%
  kableExtra::add_header_above(c(
    " " = 1, "\u2266 10days" = 1,
    "\u2266 20days" = 1, "\u2266 30days" = 1,
    "\u2266 40days" = 1, "\u2266 85days" = 1
  )) %>%
  kableExtra::column_spec(2:6, width = "5em") %>%
  kableExtra::group_rows(
    "F-tests, p-value", 8, 10,
    bold = FALSE, italic = TRUE
  )
```

## X日以内返信への効果の異質性（30歳以上の男性）

```{r tab-reply-until-days-male-over30}
sub_est_until_reply <- est_until_reply %>%
  dplyr::filter(male == 1 & age30 == 0)

sub_est_until_reply %>%
  pull(est) %>%
  setNames(paste0("(", seq(length(sub_est_until_reply$est)), ")")) %>%
  modelsummary(
    stars = c("*" = 0.1, "**" = 0.05, "***" = 0.01),
    coef_map = c(
      "treatB" = "B",
      "treatC" = "C",
      "treatD" = "D"
    ),
    gof_omit = "R2|AIC|BIC|Log|Std|FE|se_type",
    add_rows = bind_rows(sub_est_until_reply$ftestBC)[, 4] %>%
      rbind(bind_rows(sub_est_until_reply$ftestBD)[, 4]) %>%
      rbind(bind_rows(sub_est_until_reply$ftestCD)[, 4]) %>%
      data.frame(term = c("B = C", "B = D", "C = D"), .)
  ) %>%
  kableExtra::kable_styling(font_size = 9) %>%
  kableExtra::add_header_above(c(
    " " = 1, "\u2266 10days" = 1,
    "\u2266 20days" = 1, "\u2266 30days" = 1,
    "\u2266 40days" = 1, "\u2266 85days" = 1
  )) %>%
  kableExtra::column_spec(2:6, width = "5em") %>%
  kableExtra::group_rows(
    "F-tests, p-value", 8, 10,
    bold = FALSE, italic = TRUE
  )
```

## X日以内返信への効果の異質性（30歳以下の男性）

```{r tab-reply-until-days-male-under30}
sub_est_until_reply <- est_until_reply %>%
  dplyr::filter(male == 1 & age30 == 1)

sub_est_until_reply %>%
  pull(est) %>%
  setNames(paste0("(", seq(length(sub_est_until_reply$est)), ")")) %>%
  modelsummary(
    stars = c("*" = 0.1, "**" = 0.05, "***" = 0.01),
    coef_map = c(
      "treatB" = "B",
      "treatC" = "C",
      "treatD" = "D"
    ),
    gof_omit = "R2|AIC|BIC|Log|Std|FE|se_type",
    add_rows = bind_rows(sub_est_until_reply$ftestBC)[, 4] %>%
      rbind(bind_rows(sub_est_until_reply$ftestBD)[, 4]) %>%
      rbind(bind_rows(sub_est_until_reply$ftestCD)[, 4]) %>%
      data.frame(term = c("B = C", "B = D", "C = D"), .)
  ) %>%
  kableExtra::kable_styling(font_size = 9) %>%
  kableExtra::add_header_above(c(
    " " = 1, "\u2266 10days" = 1,
    "\u2266 20days" = 1, "\u2266 30days" = 1,
    "\u2266 40days" = 1, "\u2266 85days" = 1
  )) %>%
  kableExtra::column_spec(2:6, width = "5em") %>%
  kableExtra::group_rows(
    "F-tests, p-value", 8, 10,
    bold = FALSE, italic = TRUE
  )
```