

```{r load-packages, include = FALSE}
library(here)
source(here("R", "_library.r"))
source(here("R", "_outcome_labels.r"))
```

```{r load-data, include = FALSE}
root <- "D:/JMDPフィールド実験"

rawdt <- read_csv(
  here(root, "shaped.csv"),
  locale = locale(encoding = "cp932")
)

use <- rawdt %>%
  mutate(treat = factor(treat, levels = LETTERS[1:4]))

testdt <- use %>%
  dplyr::filter(ongoing == 0 & exg_stop_reply == 0  & prefecture != "海外") %>%
  select(
    id,
    reply,
    intention,
    days_reply,
    treat,
    RCTweek,
    month,
    week,
    toka,
    male,
    age,
    coordinate1
  ) %>%
  mutate(
    age_less30 = if_else(age <= 30, 1, 0),
    age_demean = age - mean(rawdt$age),
    days_reply = if_else(
      is.na(days_reply),
      max(use$days_reply, na.rm = TRUE),
      days_reply
    ),
    reply_full = reply,
    reply_5 = if_else(days_reply <= 5, 1, 0),
    reply_10 = if_else(days_reply <= 10, 1, 0),
    reply_20 = if_else(days_reply <= 20, 1, 0),
    reply_30 = if_else(days_reply <= 30, 1, 0),
    positive_full = intention,
    positive_5 = if_else(days_reply <= 5, intention, 0),
    positive_10 = if_else(days_reply <= 10, intention, 0),
    positive_20 = if_else(days_reply <= 20, intention, 0),
    positive_30 = if_else(days_reply <= 30, intention, 0),
    negative_full = reply * (1 - intention),
    negative_5 = if_else(days_reply <= 5, 1- intention, 0),
    negative_10 = if_else(days_reply <= 10, 1- intention, 0),
    negative_20 = if_else(days_reply <= 20, 1- intention, 0),
    negative_30 = if_else(days_reply <= 30, 1- intention, 0)
  ) %>%
  select(-reply, -intention, -days_reply) %>%
  pivot_longer(
    reply_full:negative_30,
    names_to = c("outcome", "within"),
    names_pattern = "(.*)_(.*)"
  ) %>%
  mutate(within = factor(
    within,
    levels = c("full", "5", "10", "20", "30"),
    labels = c(
      "full",
      "\u2264 5 days",
      "\u2264 10 days",
      "\u2264 20 days",
      "\u2264 30 days"
    )
  )) %>%
  mutate(outcome = factor(
    outcome,
    levels = c("reply", "positive", "negative"),
    labels = c("Reply", "Positive intention", "Negative intention")
  ))
```




```{r hetero-reply-geo, include = FALSE}
mod <- value ~ treat + age_demean + male + coordinate1 + toka +
  factor(month) + factor(week)

geohetero_reply <- testdt %>%
  group_by(outcome, within, toka) %>%
  do(est = lm_robust(
    update(mod, . ~ . - toka),
    cluster = RCTweek,
    se_type = "stata",
    data = .
  )) %>%
  mutate(
    toka = factor(
      toka,
      levels = c(0, 1),
      labels = c("Other Areas", "Tokyo, Osaka\nKanagawa, Aichi")
    ),
    N = paste0("N=", nobs(est))
  )
```

## 返信・意向

```{r plot-hetero-reply-geo, fig.width = 10, fig.height=7}
plot_list <- 2:4 %>%
  purrr::map(function(x) {
    geohetero_reply %>%
      dplyr::filter(within == "full") %>%
      rowwise(everything()) %>%
      summarize(
        subset(tidy(est), term == paste0("treat", LETTERS[x])) %>%
          select(-term, -outcome)
      ) %>%
      ggplot(aes(x = toka, y = estimate, color = outcome, shape = outcome)) +
      geom_hline(aes(yintercept = 0), linetype = 2) +
      geom_pointrange(
        aes(ymin = conf.low, ymax = conf.high),
        position = position_dodge(0.5)
      ) +
      geom_text(aes(y = -0.15, label = N), color = "black") +
      scale_y_continuous(
        breaks = seq(-0.2, 0.2, by = 0.05), limits = c(-0.17, 0.17)
      ) +
      labs(
        title = paste("Effect of Message", LETTERS[x]),
        x = "Subset",
        y = "Estimated Effects (95%CI)",
        color = "Outcomes", shape = "Outcomes"
      ) +
      simplegg()
  })

wrap_plots(plot_list, ncol = 2) +
  plot_layout(guides = "collect") &
  theme(legend.position = "bottom")
```

## X日以内返信(メッセージB)

```{r plotB-hetero-reply-within-geo, fig.width = 10, fig.height=7}
geohetero_reply %>%
  dplyr::filter(within != "full") %>%
  rowwise(everything()) %>%
  summarize(
    subset(tidy(est), term == "treatB") %>% select(-term, -outcome)
  ) %>%
  ggplot(aes(x = toka, y = estimate, color = outcome, shape = outcome)) +
    geom_hline(aes(yintercept = 0), linetype = 2) +
    geom_pointrange(
      aes(ymin = conf.low, ymax = conf.high),
      position = position_dodge(0.5)
    ) +
    geom_text(aes(y = -0.15, label = N), color = "black") +
    facet_wrap(~ within, ncol = 2) +
    scale_y_continuous(
      breaks = seq(-0.2, 0.2, by = 0.05), limits = c(-0.17, 0.17)
    ) +
    labs(
      x = "Subset",
      y = "Effect of Message B (95%CI)",
      color = "Outcomes", shape = "Outcomes"
    ) +
    simplegg()
```

## X日以内返信(メッセージC)

```{r plotC-hetero-reply-within-geo, fig.width = 10, fig.height=7}
geohetero_reply %>%
  dplyr::filter(within != "full") %>%
  rowwise(everything()) %>%
  summarize(
    subset(tidy(est), term == "treatC") %>% select(-term, -outcome)
  ) %>%
  ggplot(aes(x = toka, y = estimate, color = outcome, shape = outcome)) +
    geom_hline(aes(yintercept = 0), linetype = 2) +
    geom_pointrange(
      aes(ymin = conf.low, ymax = conf.high),
      position = position_dodge(0.5)
    ) +
    geom_text(aes(y = -0.15, label = N), color = "black") +
    facet_wrap(~ within, ncol = 2) +
    scale_y_continuous(
      breaks = seq(-0.2, 0.2, by = 0.05), limits = c(-0.17, 0.17)
    ) +
    labs(
      x = "Subset",
      y = "Effect of Message C (95%CI)",
      color = "Outcomes", shape = "Outcomes"
    ) +
    simplegg()
```

## X日以内返信(メッセージD)

```{r plotD-hetero-reply-within-geo, fig.width = 10, fig.height=7}
geohetero_reply %>%
  dplyr::filter(within != "full") %>%
  rowwise(everything()) %>%
  summarize(
    subset(tidy(est), term == "treatD") %>% select(-term, -outcome)
  ) %>%
  ggplot(aes(x = toka, y = estimate, color = outcome, shape = outcome)) +
    geom_hline(aes(yintercept = 0), linetype = 2) +
    geom_pointrange(
      aes(ymin = conf.low, ymax = conf.high),
      position = position_dodge(0.5)
    ) +
    geom_text(aes(y = -0.15, label = N), color = "black") +
    facet_wrap(~ within, ncol = 2) +
    scale_y_continuous(
      breaks = seq(-0.2, 0.2, by = 0.05), limits = c(-0.17, 0.17)
    ) +
    labs(
      x = "Subset",
      y = "Effect of Message D (95%CI)",
      color = "Outcomes", shape = "Outcomes"
    ) +
    simplegg()
```

## 返信・意向(性別×地域)

```{r hetero-reply-gender-geo, include = FALSE}
geohetero_reply <- testdt %>%
  group_by(outcome, within, toka, male) %>%
  do(est = lm_robust(
    update(mod, . ~ . - toka - male),
    cluster = RCTweek,
    se_type = "stata",
    data = .
  )) %>%
  mutate(
    pos = paste0(male, toka),
    pos = factor(
      pos,
      levels = c("01", "00", "11", "10"),
      labels = c(
        "Female\u00d7\nTOKA",
        "Female\u00d7\nOthers",
        "Male\u00d7\nTOKA",
        "Male\u00d7\nOthers"
      )
    ),
    N = paste0("N=", nobs(est))
  )
```

```{r plot-hetero-reply-gender-geo, fig.width = 10, fig.height=7}
plot_list <- 2:4 %>%
  purrr::map(function(x) {
    geohetero_reply %>%
      dplyr::filter(within == "full") %>%
      rowwise(everything()) %>%
      summarize(
        subset(tidy(est), term == paste0("treat", LETTERS[x])) %>%
          select(-term, -outcome)
      ) %>%
      ggplot(aes(x = pos, y = estimate, color = outcome, shape = outcome)) +
      geom_hline(aes(yintercept = 0), linetype = 2) +
      geom_pointrange(
        aes(ymin = conf.low, ymax = conf.high),
        position = position_dodge(0.5)
      ) +
      geom_text(aes(y = -0.15, label = N), color = "black") +
      scale_y_continuous(
        breaks = seq(-0.2, 0.2, by = 0.05), limits = c(-0.17, 0.17)
      ) +
      labs(
        title = paste("Effect of Message", LETTERS[x]),
        x = "Subset",
        y = "Estimated Effects (95%CI)",
        color = "Outcomes", shape = "Outcomes"
      ) +
      simplegg()
  })

wrap_plots(plot_list, ncol = 2) +
  plot_layout(guides = "collect") &
  theme(legend.position = "bottom")
```

## X日以内返信(メッセージB・性別×地域)

```{r plotB-hetero-reply-within-gender-geo, fig.width = 10, fig.height=7}
geohetero_reply %>%
  dplyr::filter(within != "full") %>%
  rowwise(everything()) %>%
  summarize(
    subset(tidy(est), term == "treatB") %>% select(-term, -outcome)
  ) %>%
  ggplot(aes(x = pos, y = estimate, color = outcome, shape = outcome)) +
    geom_hline(aes(yintercept = 0), linetype = 2) +
    geom_pointrange(
      aes(ymin = conf.low, ymax = conf.high),
      position = position_dodge(0.5)
    ) +
    geom_text(aes(y = -0.15, label = N), color = "black") +
    facet_wrap(~ within, ncol = 2) +
    scale_y_continuous(
      breaks = seq(-0.2, 0.2, by = 0.05), limits = c(-0.17, 0.17)
    ) +
    labs(
      x = "Subset",
      y = "Effect of Message B (95%CI)",
      color = "Outcomes", shape = "Outcomes"
    ) +
    simplegg()
```

## X日以内返信(メッセージC・性別×地域)

```{r plotC-hetero-reply-within-gender-geo, fig.width = 10, fig.height=7}
geohetero_reply %>%
  dplyr::filter(within != "full") %>%
  rowwise(everything()) %>%
  summarize(
    subset(tidy(est), term == "treatC") %>% select(-term, -outcome)
  ) %>%
  ggplot(aes(x = pos, y = estimate, color = outcome, shape = outcome)) +
    geom_hline(aes(yintercept = 0), linetype = 2) +
    geom_pointrange(
      aes(ymin = conf.low, ymax = conf.high),
      position = position_dodge(0.5)
    ) +
    geom_text(aes(y = -0.15, label = N), color = "black") +
    facet_wrap(~ within, ncol = 2) +
    scale_y_continuous(
      breaks = seq(-0.2, 0.2, by = 0.05), limits = c(-0.17, 0.17)
    ) +
    labs(
      x = "Subset",
      y = "Effect of Message C (95%CI)",
      color = "Outcomes", shape = "Outcomes"
    ) +
    simplegg()
```

## X日以内返信(メッセージD・性別×地域)

```{r plotD-hetero-reply-within-gender-geo, fig.width = 10, fig.height=7}
geohetero_reply %>%
  dplyr::filter(within != "full") %>%
  rowwise(everything()) %>%
  summarize(
    subset(tidy(est), term == "treatD") %>% select(-term, -outcome)
  ) %>%
  ggplot(aes(x = pos, y = estimate, color = outcome, shape = outcome)) +
    geom_hline(aes(yintercept = 0), linetype = 2) +
    geom_pointrange(
      aes(ymin = conf.low, ymax = conf.high),
      position = position_dodge(0.5)
    ) +
    geom_text(aes(y = -0.15, label = N), color = "black") +
    facet_wrap(~ within, ncol = 2) +
    scale_y_continuous(
      breaks = seq(-0.2, 0.2, by = 0.05), limits = c(-0.17, 0.17)
    ) +
    labs(
      x = "Subset",
      y = "Effect of Message D (95%CI)",
      color = "Outcomes", shape = "Outcomes"
    ) +
    simplegg()
```