
```{r load-packages, include = FALSE}
library(here)
source(here("R", "_library.r"))
source(here("R", "_outcome_labels.r"))
```

```{r load-data, include = FALSE}
root <- "D:/JMDPフィールド実験"

rawdt <- read_csv(
  here(root, "shaped.csv"),
  locale = locale(encoding = "cp932")
)

use <- rawdt %>%
  mutate(treat = factor(treat, levels = LETTERS[1:4]))

testdt <- use %>%
  dplyr::filter(exg_stop_reply == 0  & prefecture != "海外") %>%
  select(
    id,
    reply,
    days_reply,
    treat,
    RCTweek,
    month,
    week,
    prefecture,
    male,
    age,
    coordinate
  ) %>%
  mutate(
    prefecture = factor(prefecture, c("東京都", unique(rawdt$prefecture)[-11])),
    age_less30 = if_else(age <= 30, 1, 0),
    age_demean = age - mean(rawdt$age),
    coordinate1 = if_else(coordinate == 1, 1, 0),
    days_reply = if_else(
      is.na(days_reply),
      max(use$days_reply, na.rm = TRUE),
      days_reply
    ),
    reply10 = if_else(days_reply <= 10, 1, 0),
    reply20 = if_else(days_reply <= 20, 1, 0),
    reply30 = if_else(days_reply <= 30, 1, 0),
    reply40 = if_else(days_reply <= 40, 1, 0)
  ) %>%
  select(-reply, -days_reply) %>%
  pivot_longer(
    reply10:reply40,
    names_to = "within",
    names_prefix = "reply"
  ) %>%
  mutate(within = factor(
    within,
    levels = c("10", "20", "30", "40"),
    labels = c(
      "within 10days",
      "within 20days",
      "within 30days",
      "within 40days"
    )
  ))
```

## Linear Probability Model of Reply within $X$ days

- $X$日以内に返信したかどうかをアウトカム変数としたLinear probability modelを推定
  - $X = 10, 20, 30, 40, 85$

```{r reg-secondary, include = FALSE}
model <- value ~ treat + age_demean + male + coordinate1 + prefecture +
  factor(month) + factor(week)

est_within_reply <- testdt %>%
  group_by(within) %>%
  do(
    est = lm_robust(
      model,
      cluster = RCTweek,
      se_type = "stata",
      data = .
    ),
    ftestBC = lh_robust(
      model,
      cluster = RCTweek,
      se_type = "stata",
      linear_hypothesis = "treatB - treatC = 0",
      data = .
    )$lh %>% tidy(),
    ftestBD = lh_robust(
      model,
      cluster = RCTweek,
      se_type = "stata",
      linear_hypothesis = "treatB - treatD = 0",
      data = .
    )$lh %>% tidy(),
    ftestCD = lh_robust(
      model,
      cluster = RCTweek,
      se_type = "stata",
      linear_hypothesis = "treatC - treatD = 0",
      data = .
    )$lh %>% tidy()
  )
```

## Results

```{r tab-reg-secandary, eval = FALSE}
est_within_reply %>%
  pull(est, name = within) %>%
  modelsummary(
    output = "latex",
    stars = c("*" = 0.1, "**" = 0.05, "***" = 0.01),
    coef_map = c(
      "treatB" = "B",
      "treatC" = "C",
      "treatD" = "D"
    ),
    gof_omit = "R2|AIC|BIC|Log|Std|FE|se_type",
    add_rows = bind_rows(est_within_reply$ftestBC)$p.value %>%
      rbind(bind_rows(est_within_reply$ftestBD)$p.value) %>%
      rbind(bind_rows(est_within_reply$ftestCD)$p.value) %>%
      data.frame(term = c("B = C", "B = D", "C = D"), .)
  ) %>%
  kableExtra::kable_styling(font_size = 9) %>%
  kableExtra::column_spec(2:5, width = "6em") %>%
  kableExtra::group_rows(
    "F-tests, p-value", 8, 10,
    bold = FALSE, italic = TRUE
  )
```

## Heterogenous Effect on Reply within $X$ days by Gender x Age

- 性別と年齢（30歳以下どうか）でサンプルを分割して、
$X$日以内に返信したかどうかをアウトカム変数としたLinear probability modelを推定

```{r hetero-gender-age-secandary, include = FALSE}
est_within_reply_hetero <- testdt %>%
  group_by(within, male, age_less30) %>%
  do(est = lm_robust(
    update(model, . ~ . - male - age_demean),
    cluster = RCTweek,
    se_type = "stata",
    data = .
  )) %>%
  rowwise(within, male, age_less30) %>%
  summarize(
    estimate.B = subset(tidy(est), term == "treatB")$estimate,
    lwr_conf.B = subset(tidy(est), term == "treatB")$conf.low,
    upr_conf.B = subset(tidy(est), term == "treatB")$conf.high,
    estimate.C = subset(tidy(est), term == "treatC")$estimate,
    lwr_conf.C = subset(tidy(est), term == "treatC")$conf.low,
    upr_conf.C = subset(tidy(est), term == "treatC")$conf.high,
    estimate.D = subset(tidy(est), term == "treatD")$estimate,
    lwr_conf.D = subset(tidy(est), term == "treatD")$conf.low,
    upr_conf.D = subset(tidy(est), term == "treatD")$conf.high,
    nobs = nobs(est)
  ) %>%
  pivot_longer(
    estimate.B:upr_conf.D,
    names_to = c(".value", "treat"),
    names_pattern = "(.*).(.)"
  ) %>%
  ungroup() %>%
  mutate(
    pos = paste0(male, age_less30),
    N = paste0("N=", nobs)
  )
```

## Message B on Reply within $X$ days

```{r plotB-hetero-gender-age-secondary, fig.width = 10, fig.height=7}
est_within_reply_hetero %>%
  dplyr::filter(treat == "B") %>%
  ggplot(aes(x = pos, y = estimate)) +
    geom_hline(aes(yintercept = 0), linetype = 2) +
    geom_pointrange(aes(ymin = lwr_conf, ymax = upr_conf)) +
    geom_text(aes(y = -0.15, label = N)) +
    facet_wrap(~ within, ncol = 2) +
    scale_y_continuous(breaks = seq(-0.2, 0.2, by = 0.05)) +
    scale_x_discrete(
      breaks = c("00", "01", "10", "11"),
      labels = c(
        "Female\u00d7\n30<Age",
        "Female\u00d7\nAge\u226430",
        "Male\u00d7\n30<Age",
        "Male\u00d7\nAge\u226430"
      )
    ) +
    labs(x = "Subset", y = "Estimate (95%CI)") +
    simplegg()
```

## Message C on Reply within $X$ days

```{r plotC-hetero-gender-age-secondary, fig.width = 10, fig.height=7}
est_within_reply_hetero %>%
  dplyr::filter(treat == "C") %>%
  ggplot(aes(x = pos, y = estimate)) +
    geom_hline(aes(yintercept = 0), linetype = 2) +
    geom_pointrange(aes(ymin = lwr_conf, ymax = upr_conf)) +
    geom_text(aes(y = -0.15, label = N)) +
    facet_wrap(~ within, ncol = 2) +
    scale_y_continuous(breaks = seq(-0.2, 0.2, by = 0.05)) +
    scale_x_discrete(
      breaks = c("00", "01", "10", "11"),
      labels = c(
        "Female\u00d7\n30<Age",
        "Female\u00d7\nAge\u226430",
        "Male\u00d7\n30<Age",
        "Male\u00d7\nAge\u226430"
      )
    ) +
    labs(x = "Subset", y = "Estimate (95%CI)") +
    simplegg()
```

## Message D on Reply within $X$ days

```{r plotD-hetero-gender-age-secondary, fig.width = 10, fig.height=7}
est_within_reply_hetero %>%
  dplyr::filter(treat == "D") %>%
  ggplot(aes(x = pos, y = estimate)) +
    geom_hline(aes(yintercept = 0), linetype = 2) +
    geom_pointrange(aes(ymin = lwr_conf, ymax = upr_conf)) +
    geom_text(aes(y = -0.15, label = N)) +
    facet_wrap(~ within, ncol = 2) +
    scale_y_continuous(breaks = seq(-0.2, 0.2, by = 0.05)) +
    scale_x_discrete(
      breaks = c("00", "01", "10", "11"),
      labels = c(
        "Female\u00d7\n30<Age",
        "Female\u00d7\nAge\u226430",
        "Male\u00d7\n30<Age",
        "Male\u00d7\nAge\u226430"
      )
    ) +
    labs(x = "Subset", y = "Estimate (95%CI)") +
    simplegg()
```