
```{r load-packages, include = FALSE}
library(here)
source(here("R", "_library.r"))
source(here("R", "_outcome_labels.r"))
```

```{r load-data, include = FALSE}
root <- "D:/JMDPフィールド実験"

rawdt <- read_csv(
  here(root, "shaped.csv"),
  locale = locale(encoding = "cp932")
)

use <- rawdt %>%
  mutate(treat = factor(treat, levels = LETTERS[1:4])) %>%
  dplyr::filter(ongoing == 0 & prefecture != "海外") %>%
  dplyr::filter(exg_stop_reply == 0) %>%
  select(
    id,
    treat,
    RCTweek,
    month,
    week,
    toka,
    male,
    age,
    coordinate1,
    reply,
    positive = intention
  ) %>%
  mutate(
    negative = reply * (1 - positive),
    age_less30 = if_else(age <= 30, 1, 0),
    age_demean = age - mean(rawdt$age),
  )
```

```{r causal-forest-reply}
Y <- use$positive
X <- as.matrix(use[, c("male", "age", "coordinate1", "toka")])
W <- use$treat
G <- use$RCTweek
est <- multi_arm_causal_forest(X, Y, W, num.trees = 4000, clusters = G)

average_treatment_effect(est, "all", subset = X[, 1] == 0 & X[, 2] <= 30 & X[, 4] == 1)
```
