---
title: |
  Online Supplementary Material
  "Field experiment Using Text Messages to Promote Stem Cell Donation in Japan Marrow Donor Program"
bibliography: biblio.bib
biblio-style: agsm
output:
  bookdown::pdf_document2:
    latex_engine: pdflatex
    template: template/my-template.tex
    keep_tex: true
    toc: false
    number_sections: true
    citation_package: natbib
base-strech: 1.5
fontsize: 12pt
params:
  is_fe: TRUE
  is_cluster: FALSE
  se_type: stata
---

\listoftables
\clearpage

```{r include=FALSE}
knitr::opts_chunk$set(
  echo = FALSE,
  warning = FALSE,
  error = FALSE,
  message = FALSE,
  dev = "pdf",
  fig.width = 15,
  fig.height = 10,
  fig.pos = "t",
  out.extra = ""
)
```

```{r option, include = FALSE}
options(
  knitr.table.format = "latex",
  kableExtra.auto_format = FALSE
)
```

\appendix

\setcounter{figure}{0}
\setcounter{table}{0}
\renewcommand\thefigure{\thesection\arabic{figure}}
\renewcommand{\thetable}{\thesection\arabic{table}}
\renewcommand{\theHfigure}{\thesection\arabic{figure}}
\renewcommand{\theHtable}{\thesection\arabic{table}}
# Additional Figures and Tables {#figtab}

```{r library, include=FALSE}
library(here)
source(here("R/R6_RawData.r"))
source(here("R/R6_Schedule.r"))

options(
  knitr.kable.NA = "",
  modelsummary_stars_note = FALSE
)

data_root <- "D:/JMDPフィールド実験"
```

```{r assignment}
schedule <- Schedule$new(here(data_root, "RCT-schedule.csv"))
schedule$kable(
  title = "Assignment Schedule",
  notes = paste(
    "\\\\emph{Note}: See Table 1 in the main manuscrpit for a detailed description of the intervention of each experimental arm. The control arm is experimental arm A. The experiment was not conducted during the week beginning December 27, 2021, and ending January 3, 2022, because JMDP was closed for the New Year's holiday."
  ),
  hold = TRUE,
  font_size = 8
)
```

```{r set-class, include=FALSE}
rawdt <- RawData$new(
  here(data_root, "shape.csv"),
  treat_vars = "treat",
  treat_levels = LETTERS[1:4]
)

rawdt$add_cond_study_sample("ongoing == 0")

intervention <- list(
  "Standard notification" = c(A = "X", B = "X", C = "X", D = "X"),
  "Probability message" = c(A = "", B = "X", C = "", D = "X"),
  "Early coordination message" = c(A = "", B = "", C = "X", D = "X")
)

endpoint <- list(
  reply = "Response",
  positive = "Positive Intention",
  test = "CT",
  candidate = "Candidate Selection",
  consent = "Final Consent",
  donate = "Donation"
)

rct <- rawdt$RCT()
rct$add_intervention(intervention)
rct$add_outcome(endpoint)
if (params$is_cluster) rct$set_default_cluster("RCTweek")
rct$set_default_se_type("stata")
```

```{r smd-balance}
rct$
  smd_balance()$
  kable(
    title = "Assessing Balance by Standaridized Mean Difference",
    notes = "\\\\emph{Note}: These values represent the standardized mean differences (SMD) with the control arm (experimental arm A). Generally, covariates between two groups are balanced if the SMD is less than $0.1$.",
    hold = TRUE,
    font_size = 8
  )
```

```{r response-speed-CT, fig.cap = "Binned Scatter Plot of CT (or Reply with Positive Intention) vs. Response Days."}
reply_dt <- rct$data %>%
  filter(reply == 1 & 0 < days_reply & treat == "A")

plotdt <- reply_dt %>%
  mutate(ntile = ntile(days_reply, 20)) %>%
  group_by(ntile) %>%
  summarize(
    median_day = (max(days_reply) + min(days_reply)) / 2,
    mean_intention = mean(positive),
    mean_ct = mean(test)
  ) %>%
  pivot_longer(
    mean_intention:mean_ct,
    names_to = "outcome",
    names_prefix = "mean_",
    values_to = "mean"
  ) %>%
  mutate(
    outcome = factor(
      outcome,
      levels = c("intention", "ct"),
      labels = c("Positive intention", "CT")
    )
  )

plotdt %>%
  ggplot(aes(x = median_day, y = mean)) +
    geom_point(aes(shape = outcome), color = "grey40", size = 3) +
    geom_smooth(
      aes(x = days_reply, y = positive),
      data = reply_dt,
      method = "glm",
      method.args = list(family = "binomial"),
      se = TRUE,
      alpha = 0.2,
      color = "black",
      linetype = 2
    ) +
    geom_smooth(
      aes(x = days_reply, y = test),
      data = reply_dt,
      method = "glm",
      method.args = list(family = "binomial"),
      se = TRUE,
      alpha = 0.2,
      color = "black",
      linetype = 1
    ) +
    labs(x = "Response days", y = "Proportion", shape = "Outcome") +
    my_theme_classic(size = 20) +
    theme(legend.position = "bottom")
```

```{r eval = FALSE}
rct$
  flow(outcome = "positive", sample_drop = FALSE)$
  fit(days = 1:15, scale = 100)$
  plot(ylim = c(-7, 7), ybreaks = 5)

model <- value ~ treat + male +
  age_demean + I(age_demean^2) + coordinate +
  holidays + hospital_per_area + PB_per_area + BM_per_area

rhs <- labels(terms(model))
rhs[str_detect(rhs, "age|male")]



with(rct$data, table(days_reply, positive, useNA = "always"))

lm_robust(
  I(test * 100) ~ days_reply,
  data = subset(rct$data, positive == 1 & treat == "A")
)

lm_robust(
  days_reply ~ treat,
  # days_reply ~ treat * male + age_demean:male + I(age_demean^2):male +
  #   coordinate:male + holidays:male + hospital_per_area:male + PB_per_area:male + BM_per_area:male,
  data = subset(rct$data, positive == 1),
  se_type = "stata"
)

rct$data %>%
  # filter(reply == 1) %>%
  mutate(
    short_reply = case_when(
      reply == 0 ~ 0,
      days_reply > 3 ~ 0,
      TRUE ~ positive * 100
    ),
    young = if_else(age < 30, 1, 0),
    group = case_when(
      male == 0 & young == 1 ~ 1,
      male == 0 & young == 0 ~ 2,
      male == 1 & young == 1 ~ 3,
      male == 1 & young == 0 ~ 4
    ),
    group = factor(
      group,
      labels = c("Young female", "Older female", "Young male", "Older male")
    )
  ) %>%
  filter(reply == 0 | days_reply > 0) %>%
  lm_robust(
    short_reply ~ treat * group + age_demean:group + I(age_demean^2):group +
      coordinate:group + holidays:group + hospital_per_area:group + PB_per_area:group + BM_per_area:group,
    data = .,
    se_type = "stata"
  )
```

```{r set-test-reg-class, include=FALSE}
id <- which(names(endpoint) %in% c("test"))
lm_test <- rct$lm(id, sample_drop = FALSE)
logit_test <- rct$logit(id, sample_drop = FALSE)
```

```{r test-lm}
lm_test$
  fit(scale = 100)$
  kable(
    title = "Linear Probability Model of the CT",
    notes = "The unit of treatment effect is a percentage point. Covariates are gender, (demeaned) age, its squared term, the number of past coordinations, the number of public holidays in the assigned week and the following week, the number of hospitals per 10 square kilometers, the number of hospitals with PBSC collection per 10 square kilometers and the number of hospitals with BM collection per 10 square kilometers. Month and Week FE is month and week (the number of a week within each month) dummy variables. Region represents geographical clusters, where 41 prefectures are grouped into 10 regions, while Hokkaido, Tokyo, Kanagawa, Aichi, Osaka, and Okinawa each form their own region, resulting in 16 region dummies in total. Week (in Dec. and Jan.) consists of dummy variables indicating each week in December 2020 and January 2021 and the remaining period. We controlled winter holidays effect by Region$\\\\times$Week (in Dec. and Jan.) dummies which is the products of these region and week indicators.",
    hold = TRUE,
    font_size = 8
  )
```

```{r test-logit}
logit_test$
  fit()$
  kable(
    title = "Logit Model of the CT",
    notes = "Covariates are gender, (demeaned) age, its squared term, the number of past coordinations, the number of public holidays in the assigned week and the following week, the number of hospitals per 10 square kilometers, the number of hospitals with PBSC collection per 10 square kilometers and the number of hospitals with BM collection per 10 square kilometers. Month and Week FE is month and week (the number of a week within each month) dummy variables. We controlled winter holidays effect by Region$\\\\times$Week (in Dec. and Jan.) dummies. Region dummies represent geographical clusters, where 41 prefectures are grouped into 10 regions, while Hokkaido, Tokyo, Kanagawa, Aichi, Osaka, and Okinawa each form their own region, resulting in 16 region dummies in total. Week (in Dec. and Jan.) consists of dummy variables indicating each week in December 2020 and January 2021 and the remaining period.",
    fmt = "%.2f",
    hold = TRUE,
    font_size = 8
  )
```

```{r test-lm-interaction, include=FALSE}
lm_int_test <- lm_test$
  fit_interaction_of_gender_age(age_cut = 40, scale = 100)
```

```{r test-lm-interaction-reg}
lm_int_test$
  kable_reg(
    title = "Heterogenous Message Effects on CT",
    notes = "This tabel tests heterogenous message effects by gender and age. We created two age classes (Younger/Older) based on age 30. Covariates are the number of past coordinations, the number of public holidays in the assigned week and the following week, the number of hospitals per 10 square kilometers, the number of hospitals with PBSC collection per 10 square kilometers and the number of hospitals with BM collection per 10 square kilometers. Month and Week FE is month and week (the number of a week within each month) dummy variables. We controlled winter holidays effect by Region$\\\\times$Week (in Dec. and Jan.) dummies. Region dummies represent geographical clusters, where 41 prefectures are grouped into 10 regions, while Hokkaido, Tokyo, Kanagawa, Aichi, Osaka, and Okinawa each form their own region, resulting in 16 region dummies in total. Week (in Dec. and Jan.) consists of dummy variables indicating each week in December 2020 and January 2021 and the remaining period.",
    hold = TRUE,
    font_size = 8
  )
```

```{r test-lm-interaction-lh}
lm_int_test$
  kable_lh(
    "CT",
    title = "Linear Combination Test: Message Effects on CT for Specific Gender-Age Group",
    notes = "We performed a linear combination test on the coefficients of the linear probability model presented in Table \\\\ref{tab:test-lm-interaction-reg}. The null hypothesis for young women is that the treatment dummy is zero. The null hypothesis for the other gender-age groups is that the sum of the treatment dummy and the cross term of the treatment dummy and the gender-age group dummy is zero.",
    hold = TRUE,
    font_size = 8
  )
```

```{r test-lm-subset1}
library(xfun)

reg <- lm_test$
  fit_subset_by_gender_age(age_cut = 40, scale = 100, covariates = FALSE)$
  get_est() %>%
  arrange(male, desc(young))

mha_ct <- cache_rds(
  {
    rct$
      multiple_hypotheses_adjust("test")$
      estimate(scale = 100, B = 3000)$
      get_result()
  },
  file = "multiplicity-adjusted-p-CT.rds"
)

mha_tab <- mha_ct %>%
  select(Subgroup.id, Treated.id, List.p) %>%
  mutate(
    Treated.id = paste("Treatment", Treated.id),
    List.p = sprintf("%1.3f", List.p)
  ) %>%
  pivot_wider(names_from = Subgroup.id, values_from = List.p)

addtab <- data.frame(
  rbind(
    c("Control average", str_remove(reg$avg, "Ctrl Avg = ")),
    mha_tab
  )
)

attr(addtab, "position") <- 7:10

reg %>%
  pull(fit) %>%
  modelsummary(
    title = "Subset Regression of CT without Covariates",
    coef_map = c(
      "treatB" = "Treatment B",
      "treatC" = "Treatment C",
      "treatD" = "Treatment D"
    ),
    stars = c("***" = .01, "**" = .05, "*" = .1),
    gof_omit = "R2|AIC|BIC|Log|Std|FE|se_type",
    align = paste(c("l", rep("c", nrow(reg))), collapse = ""),
    add_rows = addtab,
    fmt = 2
  ) %>%
  kableExtra::kable_styling(font_size = 8, latex_options = "HOLD_position") %>%
  kableExtra::add_header_above(
    c(
      " ",
      "$\\\\text{Age} < 30$",
      "$30 \\\\le \\\\text{Age}$",
      "$\\\\text{Age} < 30$",
      "$30 \\\\le \\\\text{Age}$"
    ),
    escape = FALSE
  ) %>%
  kableExtra::add_header_above(c(" " = 1, "Females" = 2, "Males" = 2)) %>%
  kableExtra::add_header_above(c(" " = 1, "CT" = 4)) %>%
  kableExtra::group_rows(
    "Multiplicity-adjusted p-values", 8, 10,
    bold = FALSE, italic = TRUE
  ) %>%
  kableExtra::footnote(
    general_title = "",
    general = paste(
      "\\\\emph{Note}:",
      "* $p < 0.1$, ** $p < 0.05$, *** $p < 0.01$. The robust standard errors are in parentheses. We did not control any covariates. Multiplicity-adjusted p-values were calculated with the method proposed by \\\\cite{List2019}."
    ),
    threeparttable = TRUE,
    escape = FALSE
  )
```

```{r test-lm-subset2}
lm_test$
  fit_subset_by_gender_age(
    age_cut = 40,
    scale = 100,
    covariates = TRUE
  )$
  kable(
    title = "Subset Regression of CT with Covariates and Month and Week FE",
    notes = "* $p < 0.1$, ** $p < 0.05$, *** $p < 0.01$. The robust standard errors are in parentheses. We controlled the number of past coordinations, the number of public holidays in the assigned week and the following week, the number of hospitals per 10 square kilometers, the number of hospitals with PBSC collection per 10 square kilometers and the number of hospitals with BM collection per 10 square kilometers, and month and week (the number of a week within each month) dummy variables.",
    hold = TRUE,
    font_size = 8
  )
```

```{r test-lm-subset3, eval=FALSE}
lm_test$
  fit_subset_by_gender_age(
    age_cut = 40,
    scale = 100,
    covariates = TRUE,
    month_week_fe = FALSE
  )$
  kable(
    title = "Subset Regression of CT Controlling Covariates and Winter Holidays",
    notes = "* $p < 0.1$, ** $p < 0.05$, *** $p < 0.01$. The robust standard errors are in parentheses. Covariates are the number of past coordinations, the number of public holidays in the assigned week and the following week, the number of hospitals per 10 square kilometers, the number of hospitals with PBSC collection per 10 square kilometers and the number of hospitals with BM collection per 10 square kilometers. We also controlled winter holidays effect by Region$\\\\times$Week (in Dec. and Jan.) dummies. Region dummies represent geographical clusters, where 41 prefectures are grouped into 10 regions, while Hokkaido, Tokyo, Kanagawa, Aichi, Osaka, and Okinawa each form their own region, resulting in 16 region dummies in total. Week (in Dec. and Jan.) consists of dummy variables indicating each week in December 2020 and January 2021 and the remaining period.",
    hold = TRUE,
    font_size = 8
  )
```

```{r set-test-decompose-class, include=FALSE}
lm_test_decompose <- rct$decompose_effect("test")
lm_test_decompose_int <- lm_test_decompose$fit_interaction_of_gender_age(age_cut = 40, scale = 100)
```

```{r test-decompose}
lm_test_decompose$
  fit(scale = 100)$
  kable(
    title = "Decompose Effect on the CT",
    notes = "The outcome ``No exogenous attrition'' is a dummy variable that takes a value of 1 if coordination was not interrupted due to exogenous reasons (patient-side reasons) between reply with positive intention and CT. The outcome ``No endogenous attrition'' is a dummy variable that takes a value of 1 if coordination was not interrupted due to other reasons (mainly donor-side reasons). Covariates are gender, (demeaned) age, its squared term, the number of past coordinations, the number of public holidays in the assigned week and the following week, the number of hospitals per 10 square kilometers, the number of hospitals with PBSC collection per 10 square kilometers and the number of hospitals with BM collection per 10 square kilometers. Month and Week FE is month and week (the number of a week within each month) dummy variables.",
    hold = TRUE,
    font_size = 8
  )
```

```{r test-decompose-interaction-reg}
lm_test_decompose_int$
  kable_reg(
    title = "Heterogenity of Decomposing Effect on the CT",
    notes = "We created two age classes (Younger/Older) based on age 40. The outcome ``No exogenous attrition'' is a dummy variable that takes a value of 1 if coordination was not interrupted due to exogenous reasons (patient-side reasons) between reply with positive intention and CT. The outcome ``No endogenous attrition'' is a dummy variable that takes a value of 1 if coordination was not interrupted due to other reasons (mainly donor-side reasons). Covariates are the number of past coordinations, the number of public holidays in the assigned week and the following week, the number of hospitals per 10 square kilometers, the number of hospitals with PBSC collection per 10 square kilometers and the number of hospitals with BM collection per 10 square kilometers.",
    hold = TRUE,
    font_size = 8
  )
```

```{r test-decompose-interaction-lh1}
lm_test_decompose_int$
  kable_lh(
    "Positive Intention",
    title = "Linear Combination Test: Message Effects on Reply with Positive Intention for Specific Gender-Age Group",
    notes = "We performed a linear combination test on the coefficients of the linear probability model presented in Table \\\\ref{tab:test-decompose-interaction-reg}. The null hypothesis for young women is that the treatment dummy is zero. The null hypothesis for the other gender-age groups is that the sum of the treatment dummy and the cross term of the treatment dummy and the gender-age group dummy is zero.",
    hold = TRUE,
    font_size = 8
  )
```

```{r test-decompose-interaction-lh2}
lm_test_decompose_int$
  kable_lh(
    "No endogenous attrition",
    title = "Linear Combination Test: Message Effects on No Endogenous Attrition between Reply with Positive Intention and CT for Specific Gender-Age Group",
    notes = "We performed a linear combination test on the coefficients of the linear probability model presented in Table \\\\ref{tab:test-decompose-interaction-reg}. The null hypothesis for young women is that the treatment dummy is zero. The null hypothesis for the other gender-age groups is that the sum of the treatment dummy and the cross term of the treatment dummy and the gender-age group dummy is zero.",
    hold = TRUE,
    font_size = 8
  )
```

```{r set-reply-class, include=FALSE, eval=FALSE}
id_reply <- which(names(endpoint) %in% c("reply", "positive"))
lm_reply <- rct$lm(id_reply, sample_drop = FALSE)
logit_reply <- rct$logit(id_reply, sample_drop = FALSE)
```

```{r reply-lm, eval=FALSE}
lm_reply$
  fit(scale = 100)$
  kable(
    title = "Linear Probability Model of Response",
    notes = "The unit of treatment effect is a percentage point. Individual-level covariates are gender, (demeaned) age, its squared term, the number of past coordinations. Week-level covariates are the number of public holidays in the assigned week and the following week. Prefecture-level covariates are the number of hospitals per 10 square kilometers, the number of hospitals with PBSC collection per 10 square kilometers and the number of hospitals with BM collection per 10 square kilometers. Region represents geographical clusters, where 41 prefectures are grouped into 10 regions, while Hokkaido, Tokyo, Kanagawa, Aichi, Osaka, and Okinawa each form their own region, resulting in 16 region dummies in total. Week (in Dec. and Jan.) consists of dummy variables indicating each week in December 2020 and January 2021 and the remaining period. Region$\\\\times$Week (in Dec. and Jan.) FE represents the products of these region and week indicators.",
    hold = TRUE,
    font_size = 8
  )
```

```{r reply-logit, eval=FALSE}
logit_reply$
  fit()$
  kable(
    title = "Logit Model of Response",
    notes = "Individual-level covariates are gender, (demeaned) age, its squared term, the number of past coordinations. Week-level covariates are the number of public holidays in the assigned week and the following week. Prefecture-level covariates are the number of hospitals per 10 square kilometers, the number of hospitals with PBSC collection per 10 square kilometers and the number of hospitals with BM collection per 10 square kilometers. Region represents geographical clusters, where 41 prefectures are grouped into 10 regions, while Hokkaido, Tokyo, Kanagawa, Aichi, Osaka, and Okinawa each form their own region, resulting in 16 region dummies in total. Week (in Dec. and Jan.) consists of dummy variables indicating each week in December 2020 and January 2021 and the remaining period. Region$\\\\times$Week (in Dec. and Jan.) FE represents the products of these region and week indicators.",
    fmt = "%.2f",
    hold = TRUE,
    font_size = 8
  ) %>%
  kableExtra::landscape()
```

```{r int-lm-interaction, include=FALSE, eval=FALSE}
lm_int <- rct$
  lm(which(names(endpoint)  == "positive"), sample_drop = FALSE)

lm_int_int <- lm_int$
  fit_interaction_of_gender_age(age_cut = 40, scale = 100)
```

```{r int-lm-interaction-reg, eval=FALSE}
lm_int_int$
  kable_reg(
    title = "Heterogenous Message Effects on Intention to Donate",
    notes = "This tabel tests heterogenous message effects by gender and age. We created two age classes (Younger/Older) based on age 30. Covariates are the number of past coordinations, the number of public holidays in the assigned week and the following week, the number of hospitals per 10 square kilometers, the number of hospitals with PBSC collection per 10 square kilometers and the number of hospitals with BM collection per 10 square kilometers. Month and Week FE is month and week (the number of a week within each month) dummy variables. We controlled winter holidays effect by Region$\\\\times$Week (in Dec. and Jan.) dummies. Region dummies represent geographical clusters, where 41 prefectures are grouped into 10 regions, while Hokkaido, Tokyo, Kanagawa, Aichi, Osaka, and Okinawa each form their own region, resulting in 16 region dummies in total. Week (in Dec. and Jan.) consists of dummy variables indicating each week in December 2020 and January 2021 and the remaining period.",
    hold = TRUE,
    font_size = 8
  )
```

```{r int-lm-interaction-lh, eval=FALSE}
lm_int_int$
  kable_lh(
    "Positive Intention",
    title = "Linear Combination Test: Message Effects on Intention to Donate for Specific Gender-Age Group",
    notes = "We performed a linear combination test on the coefficients of the linear probability model presented in Table \\\\ref{tab:int-lm-interaction-reg}. The null hypothesis for young women is that the treatment dummy is zero. The null hypothesis for the other gender-age groups is that the sum of the treatment dummy and the cross term of the treatment dummy and the gender-age group dummy is zero.",
    hold = TRUE,
    font_size = 8
  )
```

```{r int-lm-subset1, eval=FALSE}
library(xfun)

reg <- lm_int$
  fit_subset_by_gender_age(age_cut = 40, scale = 100, covariates = FALSE)$
  get_est() %>%
  arrange(male, desc(young))

mha_int <- cache_rds(
  {
    rct$
      multiple_hypotheses_adjust("positive")$
      estimate(scale = 100, B = 3000)$
      get_result()
  },
  file = "multiplicity-adjusted-p-intention.rds"
)

mha_tab <- mha_int %>%
  select(Subgroup.id, Treated.id, List.p) %>%
  mutate(
    Treated.id = paste("Treatment", Treated.id),
    List.p = sprintf("%1.3f", List.p)
  ) %>%
  pivot_wider(names_from = Subgroup.id, values_from = List.p)

addtab <- data.frame(
  rbind(
    c("Control average", str_remove(reg$avg, "Ctrl Avg = ")),
    mha_tab
  )
)

attr(addtab, "position") <- 7:10

reg %>%
  pull(fit) %>%
  modelsummary(
    title = "Subset Regression of Intention to Donate without Covariates",
    coef_map = c(
      "treatB" = "Treatment B",
      "treatC" = "Treatment C",
      "treatD" = "Treatment D"
    ),
    stars = c("***" = .01, "**" = .05, "*" = .1),
    gof_omit = "R2|AIC|BIC|Log|Std|FE|se_type",
    align = paste(c("l", rep("c", nrow(reg))), collapse = ""),
    add_rows = addtab,
    fmt = 2
  ) %>%
  kableExtra::kable_styling(font_size = 8, latex_options = "HOLD_position") %>%
  kableExtra::add_header_above(
    c(
      " ",
      "$\\\\text{Age} < 30$",
      "$30 \\\\le \\\\text{Age}$",
      "$\\\\text{Age} < 30$",
      "$30 \\\\le \\\\text{Age}$"
    ),
    escape = FALSE
  ) %>%
  kableExtra::add_header_above(c(" " = 1, "Females" = 2, "Males" = 2)) %>%
  kableExtra::add_header_above(c(" " = 1, "CT" = 4)) %>%
  kableExtra::group_rows(
    "Multiplicity-adjusted p-values", 8, 10,
    bold = FALSE, italic = TRUE
  ) %>%
  kableExtra::footnote(
    general_title = "",
    general = paste(
      "\\\\emph{Note}:",
      "* $p < 0.1$, ** $p < 0.05$, *** $p < 0.01$. The robust standard errors are in parentheses. We did not control any covariates. Multiplicity-adjusted p-values were calculated with the method proposed by \\\\cite{List2019}."
    ),
    threeparttable = TRUE,
    escape = FALSE
  )
```

```{r int-lm-subset2, eval=FALSE}
lm_int$
  fit_subset_by_gender_age(
    age_cut = 40,
    scale = 100,
    covariates = TRUE
  )$
  kable(
    title = "Subset Regression of Intention to Donate with Covariates and Month and Week FE",
    notes = "* $p < 0.1$, ** $p < 0.05$, *** $p < 0.01$. The robust standard errors are in parentheses. We controlled the number of past coordinations, the number of public holidays in the assigned week and the following week, the number of hospitals per 10 square kilometers, the number of hospitals with PBSC collection per 10 square kilometers and the number of hospitals with BM collection per 10 square kilometers, and month and week (the number of a week within each month) dummy variables.",
    hold = TRUE,
    font_size = 8
  )
```

```{r int-lm-subset3, eval=FALSE}
lm_int$
  fit_subset_by_gender_age(
    age_cut = 40,
    scale = 100,
    covariates = TRUE,
    month_week_fe = FALSE
  )$
  kable(
    title = "Subset Regression of Intention to Donate Controlling Covariates and Winter Holidays",
    notes = "* $p < 0.1$, ** $p < 0.05$, *** $p < 0.01$. The robust standard errors are in parentheses. Covariates are the number of past coordinations, the number of public holidays in the assigned week and the following week, the number of hospitals per 10 square kilometers, the number of hospitals with PBSC collection per 10 square kilometers and the number of hospitals with BM collection per 10 square kilometers. We also controlled winter holidays effect by Region$\\\\times$Week (in Dec. and Jan.) dummies. Region dummies represent geographical clusters, where 41 prefectures are grouped into 10 regions, while Hokkaido, Tokyo, Kanagawa, Aichi, Osaka, and Okinawa each form their own region, resulting in 16 region dummies in total. Week (in Dec. and Jan.) consists of dummy variables indicating each week in December 2020 and January 2021 and the remaining period.",
    hold = TRUE,
    font_size = 8
  )
```

```{r set-lm-class-coordination, include=FALSE}
id_coordinate <- which(names(endpoint) %in% c("candidate", "consent", "donate"))
lm_coordinate <- rct$lm(id_coordinate, sample_drop = FALSE)
logit_coordinate <- rct$logit(id_coordinate, sample_drop = FALSE)
```

```{r coordinate-reg}
lm_coordinate$
  fit(scale = 100)$
  kable(
    title = "Linear Probability Model of Coordination",
    notes = "The unit of treatment effect is a percentage point. Individual-level covariates are gender, (demeaned) age, its squared term, the number of past coordinations. Week-level covariates are the number of public holidays in the assigned week and the following week. Prefecture-level covariates are the number of hospitals per 10 square kilometers, the number of hospitals with PBSC collection per 10 square kilometers and the number of hospitals with BM collection per 10 square kilometers. Region represents geographical clusters, where 41 prefectures are grouped into 10 regions, while Hokkaido, Tokyo, Kanagawa, Aichi, Osaka, and Okinawa each form their own region, resulting in 16 region dummies in total. Week (in Dec. and Jan.) consists of dummy variables indicating each week in December 2020 and January 2021 and the remaining period. Region$\\\\times$Week (in Dec. and Jan.) FE represents the products of these region and week indicators.",
    hold = TRUE,
    font_size = 8
  )
```

```{r coordinate-logit}
logit_coordinate$
  fit()$
  kable(
    title = "Logit Model of Coordination",
    notes = "Individual-level covariates are gender, (demeaned) age, its squared term, the number of past coordinations. Week-level covariates are the number of public holidays in the assigned week and the following week. Prefecture-level covariates are the number of hospitals per 10 square kilometers, the number of hospitals with PBSC collection per 10 square kilometers and the number of hospitals with BM collection per 10 square kilometers. Region represents geographical clusters, where 41 prefectures are grouped into 10 regions, while Hokkaido, Tokyo, Kanagawa, Aichi, Osaka, and Okinawa each form their own region, resulting in 16 region dummies in total. Week (in Dec. and Jan.) consists of dummy variables indicating each week in December 2020 and January 2021 and the remaining period. Region$\\\\times$Week (in Dec. and Jan.) FE represents the products of these region and week indicators.",
    fmt = "%.2f",
    hold = TRUE,
    font_size = 8
  ) %>%
  kableExtra::landscape()
```

```{r consent-lm-interaction, include=FALSE}
lm_consent <- rct$
  lm(which(names(endpoint)  == "consent"), sample_drop = FALSE)

lm_consent_int <- lm_consent$
  fit_interaction_of_gender_age(age_cut = 40, scale = 100)
```

```{r consent-lm-interaction-reg}
lm_consent_int$
  kable_reg(
    title = "Heterogenous Message Effects on Final Consent",
    notes = "This tabel tests heterogenous message effects by gender and age. We created two age classes (Younger/Older) based on age 30. Covariates are the number of past coordinations, the number of public holidays in the assigned week and the following week, the number of hospitals per 10 square kilometers, the number of hospitals with PBSC collection per 10 square kilometers and the number of hospitals with BM collection per 10 square kilometers. Month and Week FE is month and week (the number of a week within each month) dummy variables. We controlled winter holidays effect by Region$\\\\times$Week (in Dec. and Jan.) dummies. Region dummies represent geographical clusters, where 41 prefectures are grouped into 10 regions, while Hokkaido, Tokyo, Kanagawa, Aichi, Osaka, and Okinawa each form their own region, resulting in 16 region dummies in total. Week (in Dec. and Jan.) consists of dummy variables indicating each week in December 2020 and January 2021 and the remaining period.",
    hold = TRUE,
    font_size = 8
  )
```

```{r consent-lm-interaction-lh}
lm_consent_int$
  kable_lh(
    "Final Consent",
    title = "Linear Combination Test: Message Effects on Final Consent for Specific Gender-Age Group",
    notes = "We performed a linear combination test on the coefficients of the linear probability model presented in Table \\\\ref{tab:consent-lm-interaction-reg}. The null hypothesis for young women is that the treatment dummy is zero. The null hypothesis for the other gender-age groups is that the sum of the treatment dummy and the cross term of the treatment dummy and the gender-age group dummy is zero.",
    hold = TRUE,
    font_size = 8
  )
```

```{r consent-lm-subset1}
library(xfun)

reg <- lm_consent$
  fit_subset_by_gender_age(age_cut = 40, scale = 100, covariates = FALSE)$
  get_est() %>%
  arrange(male, desc(young))

mha_consent <- cache_rds(
  {
    rct$
      multiple_hypotheses_adjust("consent")$
      estimate(scale = 100, B = 3000)$
      get_result()
  },
  file = "multiplicity-adjusted-p-consent.rds"
)

mha_tab <- mha_consent %>%
  select(Subgroup.id, Treated.id, List.p) %>%
  mutate(
    Treated.id = paste("Treatment", Treated.id),
    List.p = sprintf("%1.3f", List.p)
  ) %>%
  pivot_wider(names_from = Subgroup.id, values_from = List.p)

addtab <- data.frame(
  rbind(
    c("Control average", str_remove(reg$avg, "Ctrl Avg = ")),
    mha_tab
  )
)

attr(addtab, "position") <- 7:10

reg %>%
  pull(fit) %>%
  modelsummary(
    title = "Subset Regression of Final Consent without Covariates",
    coef_map = c(
      "treatB" = "Treatment B",
      "treatC" = "Treatment C",
      "treatD" = "Treatment D"
    ),
    stars = c("***" = .01, "**" = .05, "*" = .1),
    gof_omit = "R2|AIC|BIC|Log|Std|FE|se_type",
    align = paste(c("l", rep("c", nrow(reg))), collapse = ""),
    add_rows = addtab,
    fmt = 2
  ) %>%
  kableExtra::kable_styling(font_size = 8, latex_options = "HOLD_position") %>%
  kableExtra::add_header_above(
    c(
      " ",
      "$\\\\text{Age} < 30$",
      "$30 \\\\le \\\\text{Age}$",
      "$\\\\text{Age} < 30$",
      "$30 \\\\le \\\\text{Age}$"
    ),
    escape = FALSE
  ) %>%
  kableExtra::add_header_above(c(" " = 1, "Females" = 2, "Males" = 2)) %>%
  kableExtra::add_header_above(c(" " = 1, "CT" = 4)) %>%
  kableExtra::group_rows(
    "Multiplicity-adjusted p-values", 8, 10,
    bold = FALSE, italic = TRUE
  ) %>%
  kableExtra::footnote(
    general_title = "",
    general = paste(
      "\\\\emph{Note}:",
      "* $p < 0.1$, ** $p < 0.05$, *** $p < 0.01$. The robust standard errors are in parentheses. We did not control any covariates. Multiplicity-adjusted p-values were calculated with the method proposed by \\\\cite{List2019}."
    ),
    threeparttable = TRUE,
    escape = FALSE
  )
```

```{r consent-lm-subset2}
lm_consent$
  fit_subset_by_gender_age(
    age_cut = 40,
    scale = 100,
    covariates = TRUE
  )$
  kable(
    title = "Subset Regression of Final Consent with Covariates and Month and Week FE",
    notes = "* $p < 0.1$, ** $p < 0.05$, *** $p < 0.01$. The robust standard errors are in parentheses. We controlled the number of past coordinations, the number of public holidays in the assigned week and the following week, the number of hospitals per 10 square kilometers, the number of hospitals with PBSC collection per 10 square kilometers and the number of hospitals with BM collection per 10 square kilometers, and month and week (the number of a week within each month) dummy variables.",
    hold = TRUE,
    font_size = 8
  )
```

```{r consent-lm-subset3, eval=FALSE}
lm_consent$
  fit_subset_by_gender_age(
    age_cut = 40,
    scale = 100,
    covariates = TRUE,
    month_week_fe = FALSE
  )$
  kable(
    title = "Subset Regression of Final Consent Controlling Covariates and Winter Holidays",
    notes = "* $p < 0.1$, ** $p < 0.05$, *** $p < 0.01$. The robust standard errors are in parentheses. Covariates are the number of past coordinations, the number of public holidays in the assigned week and the following week, the number of hospitals per 10 square kilometers, the number of hospitals with PBSC collection per 10 square kilometers and the number of hospitals with BM collection per 10 square kilometers. We also controlled winter holidays effect by Region$\\\\times$Week (in Dec. and Jan.) dummies. Region dummies represent geographical clusters, where 41 prefectures are grouped into 10 regions, while Hokkaido, Tokyo, Kanagawa, Aichi, Osaka, and Okinawa each form their own region, resulting in 16 region dummies in total. Week (in Dec. and Jan.) consists of dummy variables indicating each week in December 2020 and January 2021 and the remaining period.",
    hold = TRUE,
    font_size = 8
  )
```



<!-- \clearpage
# Analysis Limited to Initial Matched Candidates -->

```{r set-class-initial-matched, include=FALSE}
rawdt2 <- rawdt$clone()
rawdt2$add_cond_study_sample("ongoing == 0")
rawdt2$add_cond_study_sample("coordinate == 1")
rct_initial <- rawdt2$RCT()
rct_initial$add_intervention(intervention)
rct_initial$add_outcome(endpoint)
if (params$is_cluster) rct_initial$set_default_cluster("RCTweek")
rct_initial$set_default_se_type(params$se_type)
```

```{r reg-test-initial-matched, include=FALSE}
lm_initial_1 <- rct_initial$lm(id, sample_drop = FALSE)
logit_initial_1 <- rct_initial$logit(id, sample_drop = FALSE)
```

```{r lm-test-initial-matched}
lm_initial_1$
  fit(scale = 100)$
  kable(
    title = "Linear Probability Model of the CT (Only Initial Matched Candidates)",
    notes = "The unit of treatment effect is a percentage point. Individual-level covariates are gender, (demeaned) age, its squared term, the number of past coordinations. Week-level covariates are the number of public holidays in the assigned week and the following week. Prefecture-level covariates are the number of hospitals per 10 square kilometers, the number of hospitals with PBSC collection per 10 square kilometers and the number of hospitals with BM collection per 10 square kilometers. Region represents geographical clusters, where 41 prefectures are grouped into 10 regions, while Hokkaido, Tokyo, Kanagawa, Aichi, Osaka, and Okinawa each form their own region, resulting in 16 region dummies in total. Week (in Dec. and Jan.) consists of dummy variables indicating each week in December 2020 and January 2021 and the remaining period. Region$\\\\times$Week (in Dec. and Jan.) FE represents the products of these region and week indicators.",
    hold = TRUE,
    font_size = 8
  )
```

```{r logit-test-initial-matched}
logit_initial_1$
  fit()$
  kable(
    title = "Logit Model of the CT (Only Initial Matched Candidates)",
    notes = "Individual-level covariates are gender, (demeaned) age, its squared term, the number of past coordinations. Week-level covariates are the number of public holidays in the assigned week and the following week. Prefecture-level covariates are the number of hospitals per 10 square kilometers, the number of hospitals with PBSC collection per 10 square kilometers and the number of hospitals with BM collection per 10 square kilometers. Region represents geographical clusters, where 41 prefectures are grouped into 10 regions, while Hokkaido, Tokyo, Kanagawa, Aichi, Osaka, and Okinawa each form their own region, resulting in 16 region dummies in total. Week (in Dec. and Jan.) consists of dummy variables indicating each week in December 2020 and January 2021 and the remaining period. Region$\\\\times$Week (in Dec. and Jan.) FE represents the products of these region and week indicators.",
    fmt = "%.2f",
    hold = TRUE,
    font_size = 8
  ) %>%
  kableExtra::landscape()
```

```{r lm-test-interaction-init, include=FALSE}
lm_test_init <- rct_initial$
  lm(id, sample_drop = FALSE)

lm_int_test_init <- lm_test_init$
  fit_interaction_of_gender_age(age_cut = 40, scale = 100)
```

```{r lm-test-interaction-init-reg}
lm_int_test_init$
  kable_reg(
    title = "Heterogenous Message Effects on CT (Only Initially Matched Candidates)",
    notes = "This tabel tests heterogenous message effects by gender and age. We created two age classes (Younger/Older) based on age 30. Covariates are the number of past coordinations, the number of public holidays in the assigned week and the following week, the number of hospitals per 10 square kilometers, the number of hospitals with PBSC collection per 10 square kilometers and the number of hospitals with BM collection per 10 square kilometers. Month and Week FE is month and week (the number of a week within each month) dummy variables. We controlled winter holidays effect by Region$\\\\times$Week (in Dec. and Jan.) dummies. Region dummies represent geographical clusters, where 41 prefectures are grouped into 10 regions, while Hokkaido, Tokyo, Kanagawa, Aichi, Osaka, and Okinawa each form their own region, resulting in 16 region dummies in total. Week (in Dec. and Jan.) consists of dummy variables indicating each week in December 2020 and January 2021 and the remaining period.",
    hold = TRUE,
    font_size = 8
  )
```

```{r lm-test-interaction-init-lh}
lm_int_test_init$
  kable_lh(
    "CT",
    title = "Linear Combination Test: Message Effects on CT for Specific Gender-Age Group (Only Initially Matched Candidates)",
    notes = "We performed a linear combination test on the coefficients of the linear probability model presented in Table \\\\ref{tab:lm-test-interaction-init-reg}. The null hypothesis for young women is that the treatment dummy is zero. The null hypothesis for the other gender-age groups is that the sum of the treatment dummy and the cross term of the treatment dummy and the gender-age group dummy is zero.",
    hold = TRUE,
    font_size = 8
  )
```

```{r lm-test-subset1-init}
library(xfun)

reg <- lm_test_init$
  fit_subset_by_gender_age(age_cut = 40, scale = 100, covariates = FALSE)$
  get_est() %>%
  arrange(male, desc(young))

mha_ct_init <- cache_rds(
  {
    rct$
      multiple_hypotheses_adjust("test")$
      estimate(scale = 100, B = 3000)$
      get_result()
  },
  file = "multiplicity-adjusted-p-CT-initial.rds"
)

mha_tab <- mha_ct_init %>%
  select(Subgroup.id, Treated.id, List.p) %>%
  mutate(
    Treated.id = paste("Treatment", Treated.id),
    List.p = sprintf("%1.3f", List.p)
  ) %>%
  pivot_wider(names_from = Subgroup.id, values_from = List.p)

addtab <- data.frame(
  rbind(
    c("Control average", str_remove(reg$avg, "Ctrl Avg = ")),
    mha_tab
  )
)

attr(addtab, "position") <- 7:10

reg %>%
  pull(fit) %>%
  modelsummary(
    title = "Subset Regression of CT without Covariates (Only Initially Matched Candidates)",
    coef_map = c(
      "treatB" = "Treatment B",
      "treatC" = "Treatment C",
      "treatD" = "Treatment D"
    ),
    stars = c("***" = .01, "**" = .05, "*" = .1),
    gof_omit = "R2|AIC|BIC|Log|Std|FE|se_type",
    align = paste(c("l", rep("c", nrow(reg))), collapse = ""),
    add_rows = addtab,
    fmt = 2
  ) %>%
  kableExtra::kable_styling(font_size = 8, latex_options = "HOLD_position") %>%
  kableExtra::add_header_above(
    c(
      " ",
      "$\\\\text{Age} < 30$",
      "$30 \\\\le \\\\text{Age}$",
      "$\\\\text{Age} < 30$",
      "$30 \\\\le \\\\text{Age}$"
    ),
    escape = FALSE
  ) %>%
  kableExtra::add_header_above(c(" " = 1, "Females" = 2, "Males" = 2)) %>%
  kableExtra::add_header_above(c(" " = 1, "CT" = 4)) %>%
  kableExtra::group_rows(
    "Multiplicity-adjusted p-values", 8, 10,
    bold = FALSE, italic = TRUE
  ) %>%
  kableExtra::footnote(
    general_title = "",
    general = paste(
      "\\\\emph{Note}:",
      "* $p < 0.1$, ** $p < 0.05$, *** $p < 0.01$. The robust standard errors are in parentheses. We did not control any covariates. Multiplicity-adjusted p-values were calculated with the method proposed by \\\\cite{List2019}."
    ),
    threeparttable = TRUE,
    escape = FALSE
  )
```

```{r lm-test-subset2-init}
lm_test_init$
  fit_subset_by_gender_age(
    age_cut = 40,
    scale = 100,
    covariates = TRUE
  )$
  kable(
    title = "Subset Regression of CT with Covariates and Month and Week FE (Only Initially Matched Candidates)",
    notes = "* $p < 0.1$, ** $p < 0.05$, *** $p < 0.01$. The robust standard errors are in parentheses. We controlled the number of past coordinations, the number of public holidays in the assigned week and the following week, the number of hospitals per 10 square kilometers, the number of hospitals with PBSC collection per 10 square kilometers and the number of hospitals with BM collection per 10 square kilometers, and month and week (the number of a week within each month) dummy variables.",
    hold = TRUE,
    font_size = 8
  )
```

```{r lm-test-subset3-init, eval=FALSE}
lm_test_init$
  fit_subset_by_gender_age(
    age_cut = 40,
    scale = 100,
    covariates = TRUE,
    month_week_fe = FALSE
  )$
  kable(
    title = "Subset Regression of CT Controlling Covariates and Winter Holidays (Only Initially Matched Candidates)",
    notes = "* $p < 0.1$, ** $p < 0.05$, *** $p < 0.01$. The robust standard errors are in parentheses. Covariates are the number of past coordinations, the number of public holidays in the assigned week and the following week, the number of hospitals per 10 square kilometers, the number of hospitals with PBSC collection per 10 square kilometers and the number of hospitals with BM collection per 10 square kilometers. We also controlled winter holidays effect by Region$\\\\times$Week (in Dec. and Jan.) dummies. Region dummies represent geographical clusters, where 41 prefectures are grouped into 10 regions, while Hokkaido, Tokyo, Kanagawa, Aichi, Osaka, and Okinawa each form their own region, resulting in 16 region dummies in total. Week (in Dec. and Jan.) consists of dummy variables indicating each week in December 2020 and January 2021 and the remaining period.",
    hold = TRUE,
    font_size = 8
  )
```

```{r lm-test-decompose-init, include=FALSE}
lm_test_decompose_init <- rct_initial$decompose_effect("test")
lm_int_test_decompose_init <- lm_test_decompose_init$fit_interaction_of_gender_age(age_cut = 40, scale = 100)
```

```{r test-decompose-init}
lm_test_decompose_init$
  fit(scale = 100)$
  kable(
    title = "Decompose Effect on the CT (Only Intially Matched Candidates)",
    notes = "The outcome ``No exogenous attrition'' is a dummy variable that takes a value of 1 if coordination was not interrupted due to exogenous reasons (patient-side reasons) between reply with positive intention and CT. The outcome ``No endogenous attrition'' is a dummy variable that takes a value of 1 if coordination was not interrupted due to other reasons (mainly donor-side reasons). Covariates are gender, (demeaned) age, its squared term, the number of past coordinations, the number of public holidays in the assigned week and the following week, the number of hospitals per 10 square kilometers, the number of hospitals with PBSC collection per 10 square kilometers and the number of hospitals with BM collection per 10 square kilometers. Month and Week FE is month and week (the number of a week within each month) dummy variables.",
    hold = TRUE,
    font_size = 8
  )
```

```{r test-decompose-interaction-reg-init}
lm_int_test_decompose_init$
  kable_reg(
    title = "Heterogenity of Decomposing Effect on the CT (Only Initially Matched Candidate)",
    notes = "We created two age classes (Younger/Older) based on age 40. The outcome ``No exogenous attrition'' is a dummy variable that takes a value of 1 if coordination was not interrupted due to exogenous reasons (patient-side reasons) between reply with positive intention and CT. The outcome ``No endogenous attrition'' is a dummy variable that takes a value of 1 if coordination was not interrupted due to other reasons (mainly donor-side reasons). Covariates are the number of past coordinations, the number of public holidays in the assigned week and the following week, the number of hospitals per 10 square kilometers, the number of hospitals with PBSC collection per 10 square kilometers and the number of hospitals with BM collection per 10 square kilometers.",
    hold = TRUE,
    font_size = 8
  )
```

```{r test-decompose-interaction-lh1-init}
lm_int_test_decompose_init$
  kable_lh(
    "Positive Intention",
    title = "Linear Combination Test: Message Effects on Reply with Positive Intention for Specific Gender-Age Group (Only Initially Matched Candidate)",
    notes = "We performed a linear combination test on the coefficients of the linear probability model presented in Table \\\\ref{tab:test-decompose-interaction-reg-init}. The null hypothesis for young women is that the treatment dummy is zero. The null hypothesis for the other gender-age groups is that the sum of the treatment dummy and the cross term of the treatment dummy and the gender-age group dummy is zero.",
    hold = TRUE,
    font_size = 8
  )
```

```{r test-decompose-interaction-lh2-init}
lm_int_test_decompose_init$
  kable_lh(
    "No endogenous attrition",
    title = "Linear Combination Test: Message Effects on No Endogenous Attrition between Reply with Positive Intention and CT for Specific Gender-Age Group (Only Initially Matched Candidate)",
    notes = "We performed a linear combination test on the coefficients of the linear probability model presented in Table \\\\ref{tab:test-decompose-interaction-reg-init}. The null hypothesis for young women is that the treatment dummy is zero. The null hypothesis for the other gender-age groups is that the sum of the treatment dummy and the cross term of the treatment dummy and the gender-age group dummy is zero.",
    hold = TRUE,
    font_size = 8
  )
```

```{r lm-positive-interaction-init, include=FALSE, eval=FALSE}
lm_positive_init <- rct_initial$
  lm(which(names(endpoint) == "positive"), sample_drop = FALSE)

lm_int_positive_init <- lm_positive_init$
  fit_interaction_of_gender_age(age_cut = 40, scale = 100)
```

```{r lm-positive-interaction-init-reg, eval=FALSE}
lm_int_positive_init$
  kable_reg(
    title = "Heterogenous Message Effects on Intention to Donate (Only Initially Matched Candidates)",
    notes = "This tabel tests heterogenous message effects by gender and age. We created two age classes (Younger/Older) based on age 30. Covariates are the number of past coordinations, the number of public holidays in the assigned week and the following week, the number of hospitals per 10 square kilometers, the number of hospitals with PBSC collection per 10 square kilometers and the number of hospitals with BM collection per 10 square kilometers. Month and Week FE is month and week (the number of a week within each month) dummy variables. We controlled winter holidays effect by Region$\\\\times$Week (in Dec. and Jan.) dummies. Region dummies represent geographical clusters, where 41 prefectures are grouped into 10 regions, while Hokkaido, Tokyo, Kanagawa, Aichi, Osaka, and Okinawa each form their own region, resulting in 16 region dummies in total. Week (in Dec. and Jan.) consists of dummy variables indicating each week in December 2020 and January 2021 and the remaining period.",
    hold = TRUE,
    font_size = 8
  )
```

```{r lm-positive-interaction-init-lh, eval=FALSE}
lm_int_positive_init$
  kable_lh(
    "Positive Intention",
    title = "Linear Combination Test: Message Effects on Intention to Donate for Specific Gender-Age Group (Only Initially Matched Candidates)",
    notes = "We performed a linear combination test on the coefficients of the linear probability model presented in Table \\\\ref{tab:lm-positive-interaction-init-reg}. The null hypothesis for young women is that the treatment dummy is zero. The null hypothesis for the other gender-age groups is that the sum of the treatment dummy and the cross term of the treatment dummy and the gender-age group dummy is zero.",
    hold = TRUE,
    font_size = 8
  )
```

```{r lm-positive-subset1-init, eval=FALSE}
library(xfun)

reg <- lm_positive_init$
  fit_subset_by_gender_age(age_cut = 40, scale = 100, covariates = FALSE)$
  get_est() %>%
  arrange(male, desc(young))

mha_positive_init <- cache_rds(
  {
    rct$
      multiple_hypotheses_adjust("positive")$
      estimate(scale = 100, B = 3000)$
      get_result()
  },
  file = "multiplicity-adjusted-p-intention-initial.rds"
)

mha_tab <- mha_positive_init %>%
  select(Subgroup.id, Treated.id, List.p) %>%
  mutate(
    Treated.id = paste("Treatment", Treated.id),
    List.p = sprintf("%1.3f", List.p)
  ) %>%
  pivot_wider(names_from = Subgroup.id, values_from = List.p)

addtab <- data.frame(
  rbind(
    c("Control average", str_remove(reg$avg, "Ctrl Avg = ")),
    mha_tab
  )
)

attr(addtab, "position") <- 7:10

reg %>%
  pull(fit) %>%
  modelsummary(
    title = "Subset Regression of Intention to Donate without Covariates (Only Initially Matched Candidates)",
    coef_map = c(
      "treatB" = "Treatment B",
      "treatC" = "Treatment C",
      "treatD" = "Treatment D"
    ),
    stars = c("***" = .01, "**" = .05, "*" = .1),
    gof_omit = "R2|AIC|BIC|Log|Std|FE|se_type",
    align = paste(c("l", rep("c", nrow(reg))), collapse = ""),
    add_rows = addtab,
    fmt = 2
  ) %>%
  kableExtra::kable_styling(font_size = 8, latex_options = "HOLD_position") %>%
  kableExtra::add_header_above(
    c(
      " ",
      "$\\\\text{Age} < 30$",
      "$30 \\\\le \\\\text{Age}$",
      "$\\\\text{Age} < 30$",
      "$30 \\\\le \\\\text{Age}$"
    ),
    escape = FALSE
  ) %>%
  kableExtra::add_header_above(c(" " = 1, "Females" = 2, "Males" = 2)) %>%
  kableExtra::add_header_above(c(" " = 1, "CT" = 4)) %>%
  kableExtra::group_rows(
    "Multiplicity-adjusted p-values", 8, 10,
    bold = FALSE, italic = TRUE
  ) %>%
  kableExtra::footnote(
    general_title = "",
    general = paste(
      "\\\\emph{Note}:",
      "* $p < 0.1$, ** $p < 0.05$, *** $p < 0.01$. The robust standard errors are in parentheses. We did not control any covariates. Multiplicity-adjusted p-values were calculated with the method proposed by \\\\cite{List2019}."
    ),
    threeparttable = TRUE,
    escape = FALSE
  )
```

```{r lm-positive-subset2-init, eval=FALSE}
lm_positive_init$
  fit_subset_by_gender_age(
    age_cut = 40,
    scale = 100,
    covariates = TRUE
  )$
  kable(
    title = "Subset Regression of Intention to Donate with Covariates and Month and Week FE (Only Initially Matched Candidates)",
    notes = "* $p < 0.1$, ** $p < 0.05$, *** $p < 0.01$. The robust standard errors are in parentheses. We controlled the number of past coordinations, the number of public holidays in the assigned week and the following week, the number of hospitals per 10 square kilometers, the number of hospitals with PBSC collection per 10 square kilometers and the number of hospitals with BM collection per 10 square kilometers, and month and week (the number of a week within each month) dummy variables.",
    hold = TRUE,
    font_size = 8
  )
```

```{r lm-positive-subset3-init, eval=FALSE}
lm_positive_init$
  fit_subset_by_gender_age(
    age_cut = 40,
    scale = 100,
    covariates = TRUE,
    month_week_fe = FALSE
  )$
  kable(
    title = "Subset Regression of Intention to Donate Controlling Covariates and Winter Holidays (Only Initially Matched Candidates)",
    notes = "* $p < 0.1$, ** $p < 0.05$, *** $p < 0.01$. The robust standard errors are in parentheses. Covariates are the number of past coordinations, the number of public holidays in the assigned week and the following week, the number of hospitals per 10 square kilometers, the number of hospitals with PBSC collection per 10 square kilometers and the number of hospitals with BM collection per 10 square kilometers. We also controlled winter holidays effect by Region$\\\\times$Week (in Dec. and Jan.) dummies. Region dummies represent geographical clusters, where 41 prefectures are grouped into 10 regions, while Hokkaido, Tokyo, Kanagawa, Aichi, Osaka, and Okinawa each form their own region, resulting in 16 region dummies in total. Week (in Dec. and Jan.) consists of dummy variables indicating each week in December 2020 and January 2021 and the remaining period.",
    hold = TRUE,
    font_size = 8
  )
```

```{r reg-coordinate-initial-matched, include=FALSE}
lm_initial_2 <- rct_initial$lm(id_coordinate, sample_drop = FALSE)
logit_initial_2 <- rct_initial$logit(id_coordinate, sample_drop = FALSE)
```

```{r lm-coordinate-initial-matched}
lm_initial_2$
  fit(scale = 100)$
  kable(
    title = "Linear Probability Model of Coordination (Only Initial Matched Candidates)",
    notes = "The unit of treatment effect is a percentage point. Individual-level covariates are gender, (demeaned) age, its squared term, the number of past coordinations. Week-level covariates are the number of public holidays in the assigned week and the following week. Prefecture-level covariates are the number of hospitals per 10 square kilometers, the number of hospitals with PBSC collection per 10 square kilometers and the number of hospitals with BM collection per 10 square kilometers. Region represents geographical clusters, where 41 prefectures are grouped into 10 regions, while Hokkaido, Tokyo, Kanagawa, Aichi, Osaka, and Okinawa each form their own region, resulting in 16 region dummies in total. Week (in Dec. and Jan.) consists of dummy variables indicating each week in December 2020 and January 2021 and the remaining period. Region$\\\\times$Week (in Dec. and Jan.) FE represents the products of these region and week indicators.",
    hold = TRUE,
    font_size = 8
  )
```

```{r logit-coordinate-initial-matched}
logit_initial_2$
  fit()$
  kable(
    title = "Logit Model of Coordination (Only Initial Matched Candidates)",
    notes = "Individual-level covariates are gender, (demeaned) age, its squared term, the number of past coordinations. Week-level covariates are the number of public holidays in the assigned week and the following week. Prefecture-level covariates are the number of hospitals per 10 square kilometers, the number of hospitals with PBSC collection per 10 square kilometers and the number of hospitals with BM collection per 10 square kilometers. Region represents geographical clusters, where 41 prefectures are grouped into 10 regions, while Hokkaido, Tokyo, Kanagawa, Aichi, Osaka, and Okinawa each form their own region, resulting in 16 region dummies in total. Week (in Dec. and Jan.) consists of dummy variables indicating each week in December 2020 and January 2021 and the remaining period. Region$\\\\times$Week (in Dec. and Jan.) FE represents the products of these region and week indicators.",
    fmt = "%.2f",
    hold = TRUE,
    font_size = 8
  ) %>%
  kableExtra::landscape()
```

```{r lm-consent-interaction-init, include=FALSE}
lm_consent_init <- rct_initial$
  lm(which(names(endpoint) == "consent"), sample_drop = FALSE)

lm_int_consent_init <- lm_consent_init$
  fit_interaction_of_gender_age(age_cut = 40, scale = 100)
```

```{r lm-consent-interaction-init-reg}
lm_int_consent_init$
  kable_reg(
    title = "Heterogenous Message Effects on Final Consent (Only Initially Matched Candidates)",
    notes = "This tabel tests heterogenous message effects by gender and age. We created two age classes (Younger/Older) based on age 30. Covariates are the number of past coordinations, the number of public holidays in the assigned week and the following week, the number of hospitals per 10 square kilometers, the number of hospitals with PBSC collection per 10 square kilometers and the number of hospitals with BM collection per 10 square kilometers. Month and Week FE is month and week (the number of a week within each month) dummy variables. We controlled winter holidays effect by Region$\\\\times$Week (in Dec. and Jan.) dummies. Region dummies represent geographical clusters, where 41 prefectures are grouped into 10 regions, while Hokkaido, Tokyo, Kanagawa, Aichi, Osaka, and Okinawa each form their own region, resulting in 16 region dummies in total. Week (in Dec. and Jan.) consists of dummy variables indicating each week in December 2020 and January 2021 and the remaining period.",
    hold = TRUE,
    font_size = 8
  )
```

```{r lm-consent-interaction-init-lh}
lm_int_consent_init$
  kable_lh(
    "Final Consent",
    title = "Linear Combination Test: Message Effects on Final Consent for Specific Gender-Age Group (Only Initially Matched Candidates)",
    notes = "We performed a linear combination test on the coefficients of the linear probability model presented in Table \\\\ref{tab:lm-consent-interaction-init-reg}. The null hypothesis for young women is that the treatment dummy is zero. The null hypothesis for the other gender-age groups is that the sum of the treatment dummy and the cross term of the treatment dummy and the gender-age group dummy is zero.",
    hold = TRUE,
    font_size = 8
  )
```

```{r lm-consent-subset1-init}
library(xfun)

reg <- lm_consent_init$
  fit_subset_by_gender_age(age_cut = 40, scale = 100, covariates = FALSE)$
  get_est() %>%
  arrange(male, desc(young))

mha_consent_init <- cache_rds(
  {
    rct$
      multiple_hypotheses_adjust("consent")$
      estimate(scale = 100, B = 3000)$
      get_result()
  },
  file = "multiplicity-adjusted-p-consent-initial.rds"
)

mha_tab <- mha_consent_init %>%
  select(Subgroup.id, Treated.id, List.p) %>%
  mutate(
    Treated.id = paste("Treatment", Treated.id),
    List.p = sprintf("%1.3f", List.p)
  ) %>%
  pivot_wider(names_from = Subgroup.id, values_from = List.p)

addtab <- data.frame(
  rbind(
    c("Control average", str_remove(reg$avg, "Ctrl Avg = ")),
    mha_tab
  )
)

attr(addtab, "position") <- 7:10

reg %>%
  pull(fit) %>%
  modelsummary(
    title = "Subset Regression of Final Consent without Covariates (Only Initially Matched Candidates)",
    coef_map = c(
      "treatB" = "Treatment B",
      "treatC" = "Treatment C",
      "treatD" = "Treatment D"
    ),
    stars = c("***" = .01, "**" = .05, "*" = .1),
    gof_omit = "R2|AIC|BIC|Log|Std|FE|se_type",
    align = paste(c("l", rep("c", nrow(reg))), collapse = ""),
    add_rows = addtab,
    fmt = 2
  ) %>%
  kableExtra::kable_styling(font_size = 8, latex_options = "HOLD_position") %>%
  kableExtra::add_header_above(
    c(
      " ",
      "$\\\\text{Age} < 30$",
      "$30 \\\\le \\\\text{Age}$",
      "$\\\\text{Age} < 30$",
      "$30 \\\\le \\\\text{Age}$"
    ),
    escape = FALSE
  ) %>%
  kableExtra::add_header_above(c(" " = 1, "Females" = 2, "Males" = 2)) %>%
  kableExtra::add_header_above(c(" " = 1, "CT" = 4)) %>%
  kableExtra::group_rows(
    "Multiplicity-adjusted p-values", 8, 10,
    bold = FALSE, italic = TRUE
  ) %>%
  kableExtra::footnote(
    general_title = "",
    general = paste(
      "\\\\emph{Note}:",
      "* $p < 0.1$, ** $p < 0.05$, *** $p < 0.01$. The robust standard errors are in parentheses. We did not control any covariates. Multiplicity-adjusted p-values were calculated with the method proposed by \\\\cite{List2019}."
    ),
    threeparttable = TRUE,
    escape = FALSE
  )
```

```{r lm-consent-subset2-init}
lm_consent_init$
  fit_subset_by_gender_age(
    age_cut = 40,
    scale = 100,
    covariates = TRUE
  )$
  kable(
    title = "Subset Regression of Final Consent with Covariates and Month and Week FE (Only Initially Matched Candidates)",
    notes = "* $p < 0.1$, ** $p < 0.05$, *** $p < 0.01$. The robust standard errors are in parentheses. We controlled the number of past coordinations, the number of public holidays in the assigned week and the following week, the number of hospitals per 10 square kilometers, the number of hospitals with PBSC collection per 10 square kilometers and the number of hospitals with BM collection per 10 square kilometers, and month and week (the number of a week within each month) dummy variables.",
    hold = TRUE,
    font_size = 8
  )
```

```{r lm-consent-subset3-init, eval=FALSE}
lm_consent_init$
  fit_subset_by_gender_age(
    age_cut = 40,
    scale = 100,
    covariates = TRUE,
    month_week_fe = FALSE
  )$
  kable(
    title = "Subset Regression of Final Consent Controlling Covariates and Winter Holidays (Only Initially Matched Candidates)",
    notes = "* $p < 0.1$, ** $p < 0.05$, *** $p < 0.01$. The robust standard errors are in parentheses. Covariates are the number of past coordinations, the number of public holidays in the assigned week and the following week, the number of hospitals per 10 square kilometers, the number of hospitals with PBSC collection per 10 square kilometers and the number of hospitals with BM collection per 10 square kilometers. We also controlled winter holidays effect by Region$\\\\times$Week (in Dec. and Jan.) dummies. Region dummies represent geographical clusters, where 41 prefectures are grouped into 10 regions, while Hokkaido, Tokyo, Kanagawa, Aichi, Osaka, and Okinawa each form their own region, resulting in 16 region dummies in total. Week (in Dec. and Jan.) consists of dummy variables indicating each week in December 2020 and January 2021 and the remaining period.",
    hold = TRUE,
    font_size = 8
  )
```


<!---
# Economic Models for Predictions

In this section, we present a simple inter-temporal economic model to make predicitions of message effects. We assume that the matched donor may have the present bias, which is one of the most important insight from behaviorl economics [@Laibson1997; @ODonoghue2001].

\noindent
**Events.** Consider three periods ($t = 1, 2, 3$). At $t=1$, a matched donor receives the compatibility notice, which asks him/her to donate. The matched donor has three options: quick response (responsding at $t=1$); late response (responding at $t=2$); no response. If the matched donor responds, then the donor pays coordination cost $c$ at that time and obtains net-benefit of transplantion at the next period. The net-benefit of transplantion may be time-variant: $b_t$ if the matched donor responds at period $t$. We assume $b_1 \ge b_2$. If the matched donor does not respond, the donor does not pay any cost and receive any net-benefit.

\noindent
**Preference.** According to @Laibson1997, the utility function is $U_t = u_t + \beta \sum_{\tau = t + 1}^{3} \delta^{\tau - t} u_{\tau}$ where $\beta \in (0, 1]$ is the degree of present bias and $\delta \in (0, 1]$ is standard time discount factor. Moreover, at period $t$, the donor expect that s/he makes decisions after $t + 1$ based on $\hat{\beta} \in [\beta, 1]$. If $\beta < \hat{\beta}$, the donor falsely believes that the present bias of their future self is not as strong.

We will solve an interpersonal game [@ODonoghue2001] to obtain optimal response timing. The first result shows that the matched donor thinks that the late response is never optimal regardless of the present bias before receiving the compatibility notice ($t=0$).

\noindent
**Result 1.** For any $\beta$, $\hat{\beta}$ and $b_2$, at $t = 0$, the quick response is optimal if $b_1 \ge c/\delta$; otherwise the no response is optimal.

\noindent
*Proof.* At $t=0$, the utility of the quick response is $\beta(-\delta c + \delta^2 b_1)$, which is positive $b_1 > c / \delta$. The utility of the late response is $\beta(-\delta^2 c + \delta^3 b_2)$. Let $b_2 = b_1 - d$ for $d \ge 0$. Then, the utility of the late response is positive if $b_1 > c/\delta + d$. Note that the utility of the no response is zero. Thus, if $b_1 < c/\delta$, then the no response is optimal because the quick response and the late response produce negative utilities. The quick response is preferred to the late response if
\begin{equation}
  b_1 \ge \frac{c}{\delta} - \frac{\delta}{1-\delta}d. (\#eq:cond-t0)
\end{equation}
Thus, the quick response is optimal if $b_1 \ge c/\delta$ since the Equation (\ref{eq:cond-t0}) holds.

This resuls implies that, before receiving the compatibility notice, the matched donor thinks that the donor quickly respond to the compatibility notice if the transplantion net-benefit is sufficiently large. The next result presents that the donor may delay the response, while receiving the notice, even if the trasplantation value is sufficiently large.

\noindent
**Result 2.** Suppose that $b_1 = b_2$. At $t=1$, the quick response is optimal if $b_1 \ge c \frac{1-\beta\delta}{(1-\delta)\beta\delta}$; the late response is optimal if $c \frac{1-\beta\delta}{(1-\delta)\beta\delta} > b_1 \ge c/\beta\delta$; otherwise the no response is optimal.

\noindent
*Proof.* We employ the backward-induction to solve the interpersonal game. Consider $t=2$. If the matched donor does not choose the quick response, the donor can respond to the notice at that period. Then, the utility of the late response at $t=2$ is $-c + \beta\delta b_2$. Thus, the late response is optimal iff $b_2 \ge c/\beta\delta$. Otherwise, the donor choose the no response. Next, we go back to $t=1$ and analyze how the donor expects behavior at $t=2$. The donor believes that future selve's present bias is $\hat{\beta}$. Thus, at $t = 1$, the donor expect that s/he will respond at $t = 2$ (the late response) if and only if $b_2 \ge c/\hat{\beta}\delta$. Assuming $b_2 = b_1$, we derive the optimal choice at $t=1$ in three cases.

- Consider $b_1 < c/\hat{\beta}\delta$. Then, at $t = 1$, the donor expects to give up responding, and actually does so. Thus, the donor at $t = 1$ responds if and only if $U_1 = -c + \beta\delta b_1 \ge 0$ or $b_1 \ge c/\beta\delta$. Otherwise, the donor gives up responding. Thus, the optimal choice is the no response.
- Consider $c/\hat{\beta}\delta \le b_1 < c/\beta\delta$. Then, at $t=1$, the donor expects to respond at $t = 2$, but will not actually take that action (no response). Due to this false prediction, the donor at $t = 1$ responds if and only if $U_1 \ge \beta(-\delta c + \delta^2 b_1)$ or
\begin{equation}
  c \frac{1 - \beta\delta}{(1-\delta)\beta\delta} \le b_1. (\#eq:cond-t1)
\end{equation}
Otherwise, the donor eventually stops responding. Since $\frac{1}{\beta\delta} < \frac{1 - \beta\delta}{\beta\delta}$, the optimal choice is the no response in this case.
- Consider $c/\beta\delta \le b_1$. Then, at $t = 1$, the donor expects to respond at $t = 2$, and actually does so. Thus, the donor responds at $t = 1$ if and only if equation (\ref{eq:cond-t1}) holds. Otherwise, the donor responds at $t=2$.

This result is motivated us to create the Early Coordination message. If the net benefit of transplantion is time-invariant, then some mathced donors thinks that the quick response is ideal but acutually choose the late response or the no response. Especially, if $c/\delta \le b_1 < c/\beta\delta$, then the matched donor thinks that the quick response but does not actually respond to the compatibility notice. If $c/\beta\delta \le b_1 < c \frac{1 - \beta\delta}{(1-\delta)\beta\delta}$, then the matched donor thinks that the quick response but does delay response to the compatibility notice.

The next result shows that almost matched donor follows ideal behavior (the optimal choice at $t=0$; see Result 1) if there is sufficiently large difference between $b_1$ and $b_2$

\noindent
**Result 3.** Let $b_2 = b_1 - d$. Suppose that $c \left(\frac{1-\beta\delta}{\beta\delta} - \frac{1-\delta}{\hat{\beta}\delta} \right) < d$. Then, the matched donor actually chooses the quick response if $c/\beta\delta \le b_1$; otherwise the matched donor actually chooses the no response.
--->