---
title: |
  骨髄バンクドナーコーディネート初期行程におけるコーディネート進行率増加を目指した介入研究
author:
  - 大竹文雄（大阪大学）
  - 加藤大貴（大阪大学）
  - 黒澤彩子（伊那中央病院）
  - 吉内一浩（東京大学）
  - 福田隆浩（国立がん研究センター中央病院）
data: 2023年度第2回造血細胞移植合同班会議 令和6年1月7日(日)
output: powerpoint_presentation
---


```{r include=FALSE}
knitr::opts_chunk$set(
  echo = FALSE,
  warning = FALSE,
  error = FALSE,
  message = FALSE,
  dev = "png",
  fig.width = 15,
  fig.height = 8,
  fig.pos = "t",
  out.extra = ""
)
```

```{r library, include=FALSE}
library(here)
source(here("R/R6_RawData.r"))

data_root <- "D:/JMDPフィールド実験"
```

```{r def-study-sample, include=FALSE}
rawdt <- RawData$new(
  here(data_root, "shape.csv"),
  treat_vars = "treat",
  treat_levels = LETTERS[1:4]
)

rawdt$add_cond_study_sample("ongoing == 0")
```

```{r rct-setup, include=FALSE}
intervention <- list(
  "Standard notification" = c(A = "X", B = "X", C = "X", D = "X"),
  "Probability message" = c(A = "", B = "X", C = "", D = "X"),
  "Early Coordination message" = c(A = "", B = "", C = "X", D = "X")
)

endpoint <- list(
  reply = "Reply",
  positive = "Positive intention",
  negative = "Negative intention",
  test = "CT",
  candidate = "Candidate",
  consent = "Consent",
  donate = "Donation"
)

covs <- c(
  "Male (= 1)" = "male",
  "Age" = "age",
  "Number of past coordinations" = "coordinate",
  "Number of listed hospitals" = "hospital_per_area",
  "Number of hospitals listed with PBSC collection" = "PB_per_area",
  "Number of hospitals listed with BM collection" = "BM_per_area"
)

rct <- rawdt$RCT()
rct$add_intervention(intervention)
rct$add_outcome(endpoint)
rct$add_covariate(covs)
rct$add_fixed_effect(c("month", "week"))
rct$set_default_se_type("stata")
```

```{r rcf-int, include=FALSE}
library(xfun)
rcf <- cache_rds({
  id2 <- which(names(endpoint) == "positive")
  rct$rcf(id2)
})
```

## 一律介入と最適ターゲティングの効果

アウトカム：返信時に提供意向を示したかどうか

```{r optimum-targeting-effect}
tau <- rcf$get_tau()
positive_target <- apply(tau, 2, function(x) ifelse(x < 0, 0, x))
optimum_target <- apply(tau, 1, max)
tau <- cbind(tau, positive_target, optimum_target)
colnames(tau) <- c(
  paste0(LETTERS[2:4], "_Uniform"),
  paste0(LETTERS[2:4], "_Target"),
  "Optimum_Target"
)

tau <- data.frame(tau)

tau %>%
  pivot_longer(
    everything(),
    names_pattern = "(.*)_(.*)",
    names_to = c("treat", "target")
  ) %>%
  mutate(
    treat = factor(
      treat,
      levels = c(LETTERS[2:4], "Optimum"),
      labels = c(
        "Treatment B",
        "Treatment C",
        "Treatment D",
        "Optimum targeting"
      )
    )
  ) %>%
  datasummary(
    (` ` = treat) ~  value * target * (Mean + SD),
    data = .,
    fmt = 4,
    output = "flextable"
  ) %>%
  set_header_labels(
    "Target / Mean" = "Mean",
    "Target / SD" = "SD",
    "Uniform / Mean" = "Mean",
    "Uniform / SD" = "SD"
  ) %>%
  add_header_row(values = c("", "Targeting", "Uniform"), colwidths = c(1, 2, 2)) %>%
  align(j = -1, align = "center", part = "all") %>%
  width(j = 1, 2) %>%
  width(j = -1, 1) %>%
  ft_theme()
```

## 予測介入効果の分布

```{r dist-targeting-effect}
tau %>%
  select(B_Uniform, C_Uniform, D_Uniform, Optimum_Target) %>%
  pivot_longer(everything(), names_to = "policy", values_to = "effect") %>%
  mutate(
    policy = factor(
      policy,
      levels = c("B_Uniform", "C_Uniform", "D_Uniform", "Optimum_Target"),
      labels = c(
        "Treatment B (uniform)",
        "Treatment C (uniform)",
        "Treatment D (uniform)",
        "Optimum targeting"
      )
    ),
    positive = if_else(effect > 0, 1, 0),
    positive = factor(positive, labels = c("Non-positive effect", "Positive effect"))
  ) %>%
  ggplot(aes(x = effect, fill = positive)) +
    geom_histogram(color = "black") +
    scale_x_continuous(limits = c(-0.25, 0.25)) +
    facet_wrap(~ policy, scales = "free_x") +
    labs(x = "Predicted treatment effect", y = "Count", fill = "") +
    my_theme_classic() +
    theme(legend.position = "bottom")
```

## 最適ターゲティング別の個人属性の比較

```{r chacteristics-targeting}
X <- data.frame(rcf$get_X())
optim_treat <- apply(tau[, 1:3], 1, which.max)
X$optim <- case_when(
  optim_treat == 1 ~ "Treatment B",
  optim_treat == 2 ~ "Treatment C",
  optim_treat == 3 ~ "Treatment D",
)

tab <- table(X$optim) %>%
  data.frame() %>%
  mutate(Freq = sprintf("%1d", Freq)) %>%
  pivot_wider(names_from = Var1, values_from = Freq)

X %>%
  datasummary(
    (`Male (= 1)` = male) +
      (`Age` = age) +
      (`Number of past coordinations` = coordinate) +
      (`Number of listed hospitals` = hospital_per_area) +
      (`Number of hospitals listed with PBSC collection` = PB_per_area) +
      (`Number of hospitals listed with BM collection` = BM_per_area) ~ optim * Mean,
    data = .,
    add_rows = bind_cols(term = "N", tab),
    output = "flextable"
  ) %>%
  align(j = -1, align = "center", part = "all") %>%
  width(j = 1, 4) %>%
  width(j = -1, 1) %>%
  ft_theme()
```

## 個人属性の分布

```{r chacteristics-targeting-dist}
X %>%
  select(-male) %>%
  pivot_longer(-optim, names_to = "vars") %>%
  mutate(vars = factor(
    vars,
    levels = c("age", "coordinate", "hospital_per_area", "PB_per_area", "BM_per_area"),
    labels = c(
      "Age",
      "Number of past coordinations",
      "Number of listed hospitals",
      "Number of hospitals listed\nwith PBSC collection",
      "Number of hospitals listed\nwith BM collection"
    )
  )) %>%
  ggplot(aes(x = value, fill = optim)) +
    geom_histogram() +
    facet_wrap(~ vars, ncol = 3, scales = "free") +
    labs(fill = "Optimal treatment") +
    my_theme_classic() +
    theme(legend.position = "bottom")
```