# Decision-making Theory {-}

潜在的なドナーはいつ適合通知を返信するかという意思決定に直面している。ここで、$x_t$は$t$期に返信を示す二値変数とする。ドナーは$t=0$から$t=T$の間に一度返信するので、$\sum_{t=0}^T x_t \le 1$となる。ここで、$\sum_t x_t = 0$、すなわち、すべての期で$x_t = 0$となるのは、ドナーが適合通知に返信しないことを意味する。$t$期の効用$U(t)$は提供の現在価値$B(t)$と提供コストの現在価値$C(t)$の差、すなわち、$U(t) = B(t) - C(t)$とする。提供の現在価値は$B(t) = b\delta_b^t$とし、ここで、$b$は提供の（期待）価値、$\delta_b$は提供価値の時間割引因子とする。同様に、提供コストの現在価値は$C(t) = c\delta_c^t$とし、ここで、$c$は提供コスト、$\delta_c$は提供コストの時間割引因子である。したがって、潜在的なドナーは以下の最適化問題に直面している。
$$
\begin{equation}
\begin{split}
  &\max_{\{x_t\}_{t=0}^T} \sum_{t=0}^T x_t(b\delta_b^t - c \delta_c^t)  \\
  &\text{subject to}\quad \sum_{t = 0}^T x_t \le 1 ()
\end{split}
\end{equation}
$$ {#eq-problem}

はじめに、ドナーが適合通知に返信しないことが最適となる条件を検討する。すべての期で$U(t) < 0$となるとき、ドナーは適合通知に返信しないことが最適となる。この必要十分条件はすべての期で
$$
  b < c \left( \frac{\delta_c}{\delta_b} \right)^t
$$ {#eq-cond-noreply}
が成立していることである。ここで、$\delta_b \le \delta_c$ならば、$(\delta_c/\delta_b)^t$は$t$の増加関数であり、そうでなければ、$(\delta_c/\delta_b)^t$は$t$の減少関数となる。したがって、ドナーが適合通知に返信しないことが最適となる条件を以下の命題にまとめられる。

\noindent
**Proposition 1**. $\sum_t x_t = 0$ is optimal if and only if (a) $\delta_b \le \delta_c$ and $b < c$ or (b) $\delta_c < \delta_b$ and $b < (\delta_c/\delta_b)^T$.

\noindent
この命題は次の示唆を与えている。すなわち、提供価値$b$が十分に小さいドナー候補者は返信しないことを選択するのが最適である。ただし、いつでも助けられると考えている（$\delta_b$が十分に高い）ドナー候補者は提供価値が低くても、返信することが最適である。

我々の介入は情報提供を通じて提供価値$b$と提供価値の時間割引因子$\delta_b$を変える。確率メッセージはただ乗りできないことを通じて提供価値（$b$）を高めている。また、利他メッセージは患者の半数しか移植を受けられないことを通じて提供価値（$b$）を高め、早い返信が患者の生存確率に寄与する事実を通じて提供価値の時間割引因子（$\delta_b$）を下げている。利他メッセージの後者の効果は「今ドナー候補者になること」の価値を時間割引因子の低下によって高めている。上述の命題は我々の介入が返信行動に与える影響についての予測を立てる。確率メッセージは提供価値を高めるだけなので、ドナー候補者の返信を促すはずである。他方で、利他メッセージはドナー候補者の返信を促すと同時に、妨げてしまうかもしれない。この点を説明するために、介入によって変化した提供価値と時間割引因子をそれぞれ$\hat{b}$と$\hat{\delta}_b$とする。もし$\hat{\delta}_b < \delda_c < \delta_b$かつ$(\delta_c/\delta_b)^T < b < \hat{b} < c$となるならば、ドナー候補者は介入前に返信する意向を持っているが、介入後に返信しなくなる。すなわち、利他メッセージは「いつでも助けられる」と考えている人の返信の意向を削いでしまう。逆に、利他メッセージは介入なしに「今でないと助けられない」と考えている（$\delta_b < \delta_c$）人の返信意向を高められる。

次に、最適行動が返信となる人がいつ返信するのかについて考察する。このとき、@eq-problem の最適化問題は以下の問題に簡略化できる。
$$
\begin{equation}
  \max_t U(t) = b\delta_b^t - c \delta_c^t
\end{equation}
$$ {#eq-problem2}
この最適化問題の一階条件を得られる。
$$
\begin{equation}
  \frac{\partial U}{\partial t}(t) = b \delta_b^t \ln \delta_b - c \delta_c^t \ln\delta_c
\end{equation}
$$ {#eq-foc}
したがって、$U'(t) = 0$を満たす$t$（$t^*$と表記する）は
$$
\begin{equation}
  t^* = \frac{\ln(c/b) + \ln(\ln\delta_c/\ln\delta_b)}{\ln(\delta_b/\delta_c)}
\end{equation}
$$ {#eq-t-star}
となる。

命題1にしたがって、我々は$\delta_b \le \delta_c$と$\delta_c < \delta_b$のそれぞれの場合で$t^*$が最適であるかどうかを確認する。初めに$\delta_b \le \delta_c$の場合を考える。この選好を持つドナーについて、$b \ge c$ならば、返信が最適行動となる。したがって、$\delta_b \le \delta_c$かつ$b \ge c$のもとで$t^*$が最適解かを検証する。@eq-foc より、$t \ge t^*$で$(\partial U/\partial t)(U) \ge 0$となる。逆に、$t < t^*$で$(\partial U/\partial t)(U) < 0$となる。したがって、$t^*$は$U(t)$を最小にする。すなわち、$t^*$は最適ではなく、$t=0$もしくは$t=T$が最適である。$t=0$の効用は$U(0) = b - c$であり、$t = T$の効用は$U(T) = b \delta_b^T - c \delta_c^T$である。$\delta_b \le \delta_c$より、常に$U(0) > U(T)$を満たす。したがって、$t = 0$が最適となる。

\noindent
**Proposition 2**. $x_0 = 1$ is optimal if and only if $\delta_b \le \delta_c$ and $b \ge c$.

\noident
命題1と組み合わせると、「今でないと助けられない」と考えている（$\delta_b \le \delta_c$）人の行動は返信しないか、すぐに返信するかのどちらかである。

次に、$\delta_b > \delta_c$の場合を考える。この選好を持つドナーについて、$b\ge c(\delta_c/\delta_b)^T$ならば、返信が最適行動となる。したがって、$\delta_b > \delta_c$かつ$b\ge c(\delta_c/\delta_b)^T$のもとで$t^*$が最適解かを検証する。@eq-foc より、$t \le t^*$で$(\partial U/\partial t)(U) \ge 0$となる。逆に、$t > t^*$で$(\partial U/\partial t)(U) < 0$となる。したがって、$t^*$は$U(t)$を最大にするので、$t^*$は最適解である。ただし、$t^* \le 0$ならば、すべての$0 \le t \le T$で$(\partial U/\partial t)(U) \le 0$となるので、$t^* = 0$が最適である。また、$t^* \ge 0$ならば、すべての$0 \le t \le T$で$(\partial U/\partial t)(U) \ge 0$となるので、$t^* = T$が最適である。したがって、最適解を以下のようにまとめることができる。
$$
\begin{equation}
\begin{cases}
  x_0 = 1  &\text{if}\quad t^* \le 0 \\
  x_{t^*} = 1 &\text{if}\quad 0 < t^* < T \\
  x_T = 1  &\text{if}\quad T \le t^*
\end{cases}
\end{equation}
$$ {#eq-solution}

$t^*$が提供価値$b$や提供価値の時間割引因子$\delta_b$によってどのように変化するのかを考察する。$t = t^*$で条件づけたもとで一階条件 @eq-foc を$t$、$b$、$\delta_b$について一階微分を以下のように得る。
$$
  \frac{\partial U'}{\partial t}\biggl|_{t = t^*} 
  = b \delta_b^{t^*} (\ln\delta_b)^2 - c \delta_c^{t^*} (\ln\delta_c)^2
$$ {#eq-foc-wrt-t}
$$
  \frac{\partial U'}{\partial b}\biggl|_{t = t^*} 
  = \delta_b^{t^*} \ln\delta_b
$$ {#eq-foc-wrt-b}
$$
  \frac{\partial U'}{\partial \delta_b}\biggl|_{t = t^*}
  = b \delta_b^{t^*-1}(t^*\ln\delta_b + 1)
$$ {#eq-foc-wrt-delta}
@eq-foc-wrt-t と @eq-foc-wrt-b を用いて、陰関数定理は
$$
  \frac{dt^*}{db} = - \frac{\delta_b^{t^*} \ln\delta_b}{b \delta_b^{t^*} (\ln\delta_b)^2 - c \delta_c^{t^*} (\ln\delta_c)^2}
$$ {#eq-dtdb}
を与える。@eq-foc-wrt-t は最適化問題の二階条件なので、$t = t^*$のもとでは必ず負となる。また、$\delta_b < 1$より、@eq-foc-wrt-b も負となる。したがって、@eq-dtdb は常に負となる。同様に、@eq-foc-wrt-t と @eq-foc-wrt-delta を用いて、陰関数定理は
$$
  \frac{dt^*}{d\delta_b} = -\frac{b \delta_b^{t^*-1}(t^*\ln\delta_b + 1)}{b \delta_b^{t^*} (\ln\delta_b)^2 - c \delta_c^{t^*} (\ln\delta_c)^2}
$$ {#eq-dtdd}
を与える。よって、$t^*\ln\delta_b + 1 > 0$ならば、$\frac{dt^*}{d\delta_b} > 0$となる。この式は以下のように書き換えられる。
$$
\begin{equation}
\begin{split}
  t^* &< -\frac{1}{\ln\delta_b} \\
  \ln\left(\frac{c}{b}\right) + \ln\left(\frac{\ln\delta_c}{\ln\delta_b}\right) &< \frac{\ln\delta_c}{\ln\delta_b} - 1 \\
  \ln\left(\frac{c}{b}\right) &< \frac{\ln\delta_c}{\ln\delta_b} - \ln\left(\frac{\ln\delta_c}{\ln\delta_b}\right) - 1 \\
  \ln\left(\frac{c}{b}\right) &< F(\delta_b) - 1 \\
\end{split}
\end{equation}
$$ {#eq-cond-dtdd}
ここで、$F(\delta_b) = \ln\delta_c / \ln\delta_b - \ln(\ln\delta_c / \ln\delta_b)$であり、$F''(\delta_b) > 0$を常に満たす。$F(\delta_b)$は$\delta_b = \delta_c$で最小となり、$F(\delta_c) = 1$となる。したがって、$F(\delta_b) - 1 > 0$を常に満たす。したがって、$b > c$は$\frac{dt^*}{d\delta_b} > 0$の十分条件となる。以上の議論を以下の命題にまとめられる。

\noindent
**Propositon 3**. Suppose that $\delta_b > \delta_c$ and $b\ge c(\delta_c/\delta_b)^T$. Let $t^*$ be $t$ holding $U'(t) = 0$. Then, $x_0 = 1$ is optimal if and only if $t^* \le 0$. $x_{t^*} is optimal if and only if $0 < t^* < T$. $x_T = 1$ is optimal if and only if $T \le t^*$. $t^*$ is decreasing in $b$, and increasing in $\delta_b$ if $b > c$.

\noindent
「いつでも助けられる」と考えている人について、後で返信することが最適となりうる。情報提供の介入を通じた提供価値の上昇は早く返信するようになる。また、情報提供の介入が提供価値を大幅に高め、時間割引因子を小幅に減らすとき、介入は返信行動を早める。